/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kudobuilder/kudo/pkg/apis/kudo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFrameworkVersions implements FrameworkVersionInterface
type FakeFrameworkVersions struct {
	Fake *FakeKudoV1alpha1
	ns   string
}

var frameworkversionsResource = schema.GroupVersionResource{Group: "kudo.k8s.io", Version: "v1alpha1", Resource: "frameworkversions"}

var frameworkversionsKind = schema.GroupVersionKind{Group: "kudo.k8s.io", Version: "v1alpha1", Kind: "FrameworkVersion"}

// Get takes name of the frameworkVersion, and returns the corresponding frameworkVersion object, and an error if there is any.
func (c *FakeFrameworkVersions) Get(name string, options v1.GetOptions) (result *v1alpha1.FrameworkVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(frameworkversionsResource, c.ns, name), &v1alpha1.FrameworkVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrameworkVersion), err
}

// List takes label and field selectors, and returns the list of FrameworkVersions that match those selectors.
func (c *FakeFrameworkVersions) List(opts v1.ListOptions) (result *v1alpha1.FrameworkVersionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(frameworkversionsResource, frameworkversionsKind, c.ns, opts), &v1alpha1.FrameworkVersionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FrameworkVersionList{ListMeta: obj.(*v1alpha1.FrameworkVersionList).ListMeta}
	for _, item := range obj.(*v1alpha1.FrameworkVersionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested frameworkVersions.
func (c *FakeFrameworkVersions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(frameworkversionsResource, c.ns, opts))

}

// Create takes the representation of a frameworkVersion and creates it.  Returns the server's representation of the frameworkVersion, and an error, if there is any.
func (c *FakeFrameworkVersions) Create(frameworkVersion *v1alpha1.FrameworkVersion) (result *v1alpha1.FrameworkVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(frameworkversionsResource, c.ns, frameworkVersion), &v1alpha1.FrameworkVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrameworkVersion), err
}

// Update takes the representation of a frameworkVersion and updates it. Returns the server's representation of the frameworkVersion, and an error, if there is any.
func (c *FakeFrameworkVersions) Update(frameworkVersion *v1alpha1.FrameworkVersion) (result *v1alpha1.FrameworkVersion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(frameworkversionsResource, c.ns, frameworkVersion), &v1alpha1.FrameworkVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrameworkVersion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFrameworkVersions) UpdateStatus(frameworkVersion *v1alpha1.FrameworkVersion) (*v1alpha1.FrameworkVersion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(frameworkversionsResource, "status", c.ns, frameworkVersion), &v1alpha1.FrameworkVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrameworkVersion), err
}

// Delete takes name of the frameworkVersion and deletes it. Returns an error if one occurs.
func (c *FakeFrameworkVersions) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(frameworkversionsResource, c.ns, name), &v1alpha1.FrameworkVersion{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFrameworkVersions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(frameworkversionsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.FrameworkVersionList{})
	return err
}

// Patch applies the patch and returns the patched frameworkVersion.
func (c *FakeFrameworkVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FrameworkVersion, err error) {
	obj, err := c.Fake.
		// Invokes(testing.NewPatchSubresourceAction(frameworkversionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.FrameworkVersion{})
		Invokes(testing.NewPatchSubresourceAction(frameworkversionsResource, c.ns, name, data, subresources...), &v1alpha1.FrameworkVersion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FrameworkVersion), err
}
