name-template: 'kudo-v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ЁЯЪА Highlights'
    labels:
      - 'release/highlight'
  - title: 'тЪая╕П Breaking Changes'
    labels:
      - 'release/breaking-change'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
