name-template: 'kudo-v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'ЁЯЪА Highlights'
    labels:
      - 'release/highlight'
  - title: 'тЪая╕П Breaking Changes'
    labels:
      - 'release/breaking-change'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## Docker images

  - `docker pull kudobuilder/controller:latest`
  - `docker pull kudobuilder/controller:$NEXT_PATCH_VERSION`
