env:
  - GO111MODULE=on
  - CGO_ENABLED=0
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  binary: manager
  main: cmd/manager/main.go
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
-
  binary: kubectl-kudo
  main: cmd/kubectl-kudo/main.go
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
archives:
- replacements:
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: kudobuilder
    name: kudo
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
