env:
  - GO111MODULE=on
  - CGO_ENABLED=0
# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    # Pulls down the latest version of the controller's parent image
    - docker pull ubuntu:18.04
builds:
  - id: "manager"
    binary: manager
    main: cmd/manager/main.go
    ldflags:
      - -s -w -X github.com/kudobuilder/kudo/pkg/version.gitVersion={{ .Version }} -X github.com/kudobuilder/kudo/pkg/version.gitCommit={{ .ShortCommit }} -X github.com/kudobuilder/kudo/pkg/version.buildDate={{ .Date }}
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
  - id: "kubectl-kudo"
    binary: kubectl-kudo
    main: cmd/kubectl-kudo/main.go
    ldflags:
      - -s -w -X github.com/kudobuilder/kudo/pkg/version.gitVersion={{ .Version }} -X github.com/kudobuilder/kudo/pkg/version.gitCommit={{ .ShortCommit }} -X github.com/kudobuilder/kudo/pkg/version.buildDate={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
dockers:
  - dockerfile: Dockerfile.goreleaser
    binaries:
      - manager
    image_templates:
      - "kudobuilder/controller:latest"
      - "kudobuilder/controller:{{ .Tag }}"
    skip_push: auto
archives:
  - id: kubectl-kudo-tarball
    builds:
      - kubectl-kudo
    replacements:
      386: i386
      amd64: x86_64
    format: tar.gz
  - id: binaries
    builds:
      - manager
      - kubectl-kudo
    replacements:
      386: i386
      amd64: x86_64
    format: binary
brews:
  - name: kudo-cli
    github:
      owner: kudobuilder
      name: homebrew-tap
    commit_author:
      name: kudoreleasebot
      email: release@kudo.dev
    skip_upload: auto
    folder: Formula
    homepage: https://kudo.dev
    description: Interact with KUDO via the kubectl plugin
    dependencies:
      - kubernetes-cli
    install: |
      bin.install "kubectl-kudo"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: kudobuilder
    name: kudo
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
