FROM kudobuilder/golang:1.12

WORKDIR $GOPATH/src/github.com/kudobuilder/kudo
COPY .git-credentials .git-credentials


COPY pkg/    pkg/
COPY config/    config/
COPY cmd/    cmd/
COPY go.mod go.mod
COPY go.sum go.sum
COPY Makefile Makefile

RUN cp .git-credentials ~/.git-credentials

RUN make test