apiVersion: kudo.dev/v1beta1
kind: TestSuite
crdDir: ./config/crds/
manifestDirs:
- ./test/manifests/
testDirs:
- ./test/integration
commands:
  - command: ./bin/manager
    background: true
startControlPlane: true
parallel: 4
