apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: operatorversions.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: OperatorVersion
    plural: operatorversions
    singular: operatorversion
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            appVersion:
              type: string
            connectionString:
              description: ConnectionString defines a templated string that can be
                used to connect to an instance of the Operator.
              type: string
            crdVersion:
              type: string
            operator:
              type: object
            parameters:
              items:
                properties:
                  default:
                    description: Default is a default value if no parameter is provided
                      by the instance.
                    type: string
                  description:
                    description: Description captures a longer description of how
                      the parameter will be used.
                    type: string
                  displayName:
                    description: DisplayName can be used by UIs.
                    type: string
                  name:
                    description: "Name is the string that should be used in the template
                      file for example, if `name: COUNT` then using the variable in
                      a spec like: \n spec:   replicas:  {{ .Params.COUNT }}"
                    type: string
                  required:
                    description: Required specifies if the parameter is required to
                      be provided by all instances, or whether a default can suffice.
                    type: boolean
                  trigger:
                    description: Trigger identifies the plan that gets executed when
                      this parameter changes in the Instance object. Default is `update`
                      if a plan with that name exists, otherwise it's `deploy`.
                    type: string
                type: object
              type: array
            plans:
              description: Plans maps a plan name to a plan.
              type: object
            tasks:
              description: List of all tasks available in this OperatorVersion.
              items:
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  spec:
                    type: object
                type: object
              type: array
            templates:
              description: Templates is a list of references to YAML templates located
                in the templates folder and later referenced from tasks.
              type: object
            upgradableFrom:
              description: UpgradableFrom lists all OperatorVersions that can upgrade
                to this OperatorVersion.
              items:
                type: object
              type: array
            version:
              type: string
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
