apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: operators.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: Operator
    plural: operators
    singular: operator
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            kubernetesVersion:
              type: string
            kudoVersion:
              type: string
            maintainers:
              items:
                properties:
                  email:
                    type: string
                  name:
                    type: string
                type: object
              type: array
            url:
              type: string
          type: object
        status:
          type: object
      type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
