apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: operators.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: Operator
    plural: operators
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            kubernetesVersion:
              type: string
            kudoVersion:
              type: string
            maintainers:
              items:
                type: string
              type: array
            url:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: operatorversions.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: OperatorVersion
    plural: operatorversions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            connectionString:
              description: ConnectionString defines a mustached string that can be
                used to connect to an instance of the Operator
              type: string
            dependencies:
              items:
                properties:
                  referenceName:
                    description: Name specifies the name of the dependency.  Referenced
                      via this in defaults.config
                    type: string
                  version:
                    description: 'Version captures the requirements for what versions
                      of the above object are allowed Example: ^3.1.4'
                    type: string
                required:
                - referenceName
                - version
                type: object
              type: array
            operator:
              type: object
            parameters:
              items:
                properties:
                  default:
                    description: Default is a default value if no paramter is provided
                      by the instance
                    type: string
                  description:
                    description: Description captures a longer description of how
                      the variable will be used
                    type: string
                  displayName:
                    description: Human friendly version of the parameter name
                    type: string
                  name:
                    description: 'Name is the string that should be used in the template
                      file for example, if `name: COUNT` then using the variable in
                      a spec like:  spec:   replicas:  {{ .Params.COUNT }}'
                    type: string
                  required:
                    description: Required specifies if the parameter is required to
                      be provided by all instances, or whether a default can suffice
                    type: boolean
                  trigger:
                    description: Trigger identifies the plan that gets executed when
                      this parameter changes in the Instance object. Default is `update`
                      if present, or `deploy` if not present
                    type: string
                type: object
              type: array
            plans:
              description: Plans specify a map a plans that specify how to
              type: object
            tasks:
              type: object
            templates:
              description: List of go templates YAML files that define
                the application operator instance
              type: object
            upgradableFrom:
              description: UpgradableFrom lists all OperatorVersions that can upgrade
                to this OperatorVersion
              items:
                type: object
              type: array
            version:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: instances.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: Instance
    plural: instances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            dependencies:
              description: Dependency references specific
              items:
                properties:
                  referenceName:
                    description: Name specifies the name of the dependency.  Referenced
                      via this in defaults.config
                    type: string
                  version:
                    description: 'Version captures the requirements for what versions
                      of the above object are allowed Example: ^3.1.4'
                    type: string
                required:
                - referenceName
                - version
                type: object
              type: array
            OperatorVersion:
              description: Operator specifies a reference to a specific Operator
                object
              type: object
            parameters:
              type: object
          type: object
        status:
          properties:
            activePlan:
              description: TODO turn into struct
              type: object
            status:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: planexecutions.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: PlanExecution
    plural: planexecutions
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            instance:
              type: object
            planName:
              type: string
            suspend:
              description: This is copied from the CronJob Spec This flag tells the
                controller to suspend subsequent executions, it does not apply to
                already started executions.  Defaults to false.
              type: boolean
          required:
          - planName
          - instance
          type: object
        status:
          properties:
            name:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
            phases:
              description: Phases maps a phase name to a Phase object
              items:
                properties:
                  name:
                    type: string
                  state:
                    type: string
                  steps:
                    description: Steps maps a step name to a list of templates
                      objects stored as a string
                    items:
                      properties:
                        delete:
                          type: boolean
                        name:
                          type: string
                        state:
                          type: string
                      type: object
                    type: array
                  strategy:
                    type: string
                required:
                - steps
                type: object
              type: array
            state:
              type: string
            strategy:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
