apiVersion: kudo.dev/v1beta1
kind: PlanExecution
metadata:
  labels:
    operator-version: mysql-57
    instance: mysql
  name: mysql-restore
  namespace: default
spec:
  instance:
    kind: Instance
    name: mysql
    namespace: default
  planName: restore