// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	kudo "github.com/kudobuilder/kudo/pkg/apis/kudo"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AggregatedStatus)(nil), (*kudo.AggregatedStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_AggregatedStatus_To_kudo_AggregatedStatus(a.(*AggregatedStatus), b.(*kudo.AggregatedStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.AggregatedStatus)(nil), (*AggregatedStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_AggregatedStatus_To_v1beta1_AggregatedStatus(a.(*kudo.AggregatedStatus), b.(*AggregatedStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DummyTaskSpec)(nil), (*kudo.DummyTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DummyTaskSpec_To_kudo_DummyTaskSpec(a.(*DummyTaskSpec), b.(*kudo.DummyTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.DummyTaskSpec)(nil), (*DummyTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_DummyTaskSpec_To_v1beta1_DummyTaskSpec(a.(*kudo.DummyTaskSpec), b.(*DummyTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Instance)(nil), (*kudo.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Instance_To_kudo_Instance(a.(*Instance), b.(*kudo.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Instance)(nil), (*Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Instance_To_v1beta1_Instance(a.(*kudo.Instance), b.(*Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceError)(nil), (*kudo.InstanceError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_InstanceError_To_kudo_InstanceError(a.(*InstanceError), b.(*kudo.InstanceError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceError)(nil), (*InstanceError)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceError_To_v1beta1_InstanceError(a.(*kudo.InstanceError), b.(*InstanceError), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceList)(nil), (*kudo.InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_InstanceList_To_kudo_InstanceList(a.(*InstanceList), b.(*kudo.InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceList)(nil), (*InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceList_To_v1beta1_InstanceList(a.(*kudo.InstanceList), b.(*InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceSpec)(nil), (*kudo.InstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_InstanceSpec_To_kudo_InstanceSpec(a.(*InstanceSpec), b.(*kudo.InstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceSpec)(nil), (*InstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceSpec_To_v1beta1_InstanceSpec(a.(*kudo.InstanceSpec), b.(*InstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceStatus)(nil), (*kudo.InstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_InstanceStatus_To_kudo_InstanceStatus(a.(*InstanceStatus), b.(*kudo.InstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceStatus)(nil), (*InstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceStatus_To_v1beta1_InstanceStatus(a.(*kudo.InstanceStatus), b.(*InstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Maintainer)(nil), (*kudo.Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Maintainer_To_kudo_Maintainer(a.(*Maintainer), b.(*kudo.Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Maintainer)(nil), (*Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Maintainer_To_v1beta1_Maintainer(a.(*kudo.Maintainer), b.(*Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Operator)(nil), (*kudo.Operator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Operator_To_kudo_Operator(a.(*Operator), b.(*kudo.Operator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Operator)(nil), (*Operator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Operator_To_v1beta1_Operator(a.(*kudo.Operator), b.(*Operator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorDependency)(nil), (*kudo.OperatorDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorDependency_To_kudo_OperatorDependency(a.(*OperatorDependency), b.(*kudo.OperatorDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorDependency)(nil), (*OperatorDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorDependency_To_v1beta1_OperatorDependency(a.(*kudo.OperatorDependency), b.(*OperatorDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorList)(nil), (*kudo.OperatorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorList_To_kudo_OperatorList(a.(*OperatorList), b.(*kudo.OperatorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorList)(nil), (*OperatorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorList_To_v1beta1_OperatorList(a.(*kudo.OperatorList), b.(*OperatorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorSpec)(nil), (*kudo.OperatorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorSpec_To_kudo_OperatorSpec(a.(*OperatorSpec), b.(*kudo.OperatorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorSpec)(nil), (*OperatorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorSpec_To_v1beta1_OperatorSpec(a.(*kudo.OperatorSpec), b.(*OperatorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorStatus)(nil), (*kudo.OperatorStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorStatus_To_kudo_OperatorStatus(a.(*OperatorStatus), b.(*kudo.OperatorStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorStatus)(nil), (*OperatorStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorStatus_To_v1beta1_OperatorStatus(a.(*kudo.OperatorStatus), b.(*OperatorStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersion)(nil), (*kudo.OperatorVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorVersion_To_kudo_OperatorVersion(a.(*OperatorVersion), b.(*kudo.OperatorVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersion)(nil), (*OperatorVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersion_To_v1beta1_OperatorVersion(a.(*kudo.OperatorVersion), b.(*OperatorVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersionList)(nil), (*kudo.OperatorVersionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorVersionList_To_kudo_OperatorVersionList(a.(*OperatorVersionList), b.(*kudo.OperatorVersionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersionList)(nil), (*OperatorVersionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersionList_To_v1beta1_OperatorVersionList(a.(*kudo.OperatorVersionList), b.(*OperatorVersionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersionSpec)(nil), (*kudo.OperatorVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorVersionSpec_To_kudo_OperatorVersionSpec(a.(*OperatorVersionSpec), b.(*kudo.OperatorVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersionSpec)(nil), (*OperatorVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersionSpec_To_v1beta1_OperatorVersionSpec(a.(*kudo.OperatorVersionSpec), b.(*OperatorVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersionStatus)(nil), (*kudo.OperatorVersionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_OperatorVersionStatus_To_kudo_OperatorVersionStatus(a.(*OperatorVersionStatus), b.(*kudo.OperatorVersionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersionStatus)(nil), (*OperatorVersionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersionStatus_To_v1beta1_OperatorVersionStatus(a.(*kudo.OperatorVersionStatus), b.(*OperatorVersionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Parameter)(nil), (*kudo.Parameter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Parameter_To_kudo_Parameter(a.(*Parameter), b.(*kudo.Parameter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Parameter)(nil), (*Parameter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Parameter_To_v1beta1_Parameter(a.(*kudo.Parameter), b.(*Parameter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Phase)(nil), (*kudo.Phase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Phase_To_kudo_Phase(a.(*Phase), b.(*kudo.Phase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Phase)(nil), (*Phase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Phase_To_v1beta1_Phase(a.(*kudo.Phase), b.(*Phase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PhaseStatus)(nil), (*kudo.PhaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PhaseStatus_To_kudo_PhaseStatus(a.(*PhaseStatus), b.(*kudo.PhaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PhaseStatus)(nil), (*PhaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PhaseStatus_To_v1beta1_PhaseStatus(a.(*kudo.PhaseStatus), b.(*PhaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PipeSpec)(nil), (*kudo.PipeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PipeSpec_To_kudo_PipeSpec(a.(*PipeSpec), b.(*kudo.PipeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PipeSpec)(nil), (*PipeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PipeSpec_To_v1beta1_PipeSpec(a.(*kudo.PipeSpec), b.(*PipeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PipeTaskSpec)(nil), (*kudo.PipeTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PipeTaskSpec_To_kudo_PipeTaskSpec(a.(*PipeTaskSpec), b.(*kudo.PipeTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PipeTaskSpec)(nil), (*PipeTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PipeTaskSpec_To_v1beta1_PipeTaskSpec(a.(*kudo.PipeTaskSpec), b.(*PipeTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Plan)(nil), (*kudo.Plan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Plan_To_kudo_Plan(a.(*Plan), b.(*kudo.Plan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Plan)(nil), (*Plan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Plan_To_v1beta1_Plan(a.(*kudo.Plan), b.(*Plan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlanStatus)(nil), (*kudo.PlanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PlanStatus_To_kudo_PlanStatus(a.(*PlanStatus), b.(*kudo.PlanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PlanStatus)(nil), (*PlanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PlanStatus_To_v1beta1_PlanStatus(a.(*kudo.PlanStatus), b.(*PlanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceTaskSpec)(nil), (*kudo.ResourceTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceTaskSpec_To_kudo_ResourceTaskSpec(a.(*ResourceTaskSpec), b.(*kudo.ResourceTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.ResourceTaskSpec)(nil), (*ResourceTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_ResourceTaskSpec_To_v1beta1_ResourceTaskSpec(a.(*kudo.ResourceTaskSpec), b.(*ResourceTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Step)(nil), (*kudo.Step)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Step_To_kudo_Step(a.(*Step), b.(*kudo.Step), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Step)(nil), (*Step)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Step_To_v1beta1_Step(a.(*kudo.Step), b.(*Step), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StepStatus)(nil), (*kudo.StepStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_StepStatus_To_kudo_StepStatus(a.(*StepStatus), b.(*kudo.StepStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.StepStatus)(nil), (*StepStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_StepStatus_To_v1beta1_StepStatus(a.(*kudo.StepStatus), b.(*StepStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Task)(nil), (*kudo.Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Task_To_kudo_Task(a.(*Task), b.(*kudo.Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Task)(nil), (*Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Task_To_v1beta1_Task(a.(*kudo.Task), b.(*Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskSpec)(nil), (*kudo.TaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_TaskSpec_To_kudo_TaskSpec(a.(*TaskSpec), b.(*kudo.TaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.TaskSpec)(nil), (*TaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_TaskSpec_To_v1beta1_TaskSpec(a.(*kudo.TaskSpec), b.(*TaskSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_AggregatedStatus_To_kudo_AggregatedStatus(in *AggregatedStatus, out *kudo.AggregatedStatus, s conversion.Scope) error {
	out.Status = kudo.ExecutionStatus(in.Status)
	out.ActivePlanName = in.ActivePlanName
	return nil
}

// Convert_v1beta1_AggregatedStatus_To_kudo_AggregatedStatus is an autogenerated conversion function.
func Convert_v1beta1_AggregatedStatus_To_kudo_AggregatedStatus(in *AggregatedStatus, out *kudo.AggregatedStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_AggregatedStatus_To_kudo_AggregatedStatus(in, out, s)
}

func autoConvert_kudo_AggregatedStatus_To_v1beta1_AggregatedStatus(in *kudo.AggregatedStatus, out *AggregatedStatus, s conversion.Scope) error {
	out.Status = ExecutionStatus(in.Status)
	out.ActivePlanName = in.ActivePlanName
	return nil
}

// Convert_kudo_AggregatedStatus_To_v1beta1_AggregatedStatus is an autogenerated conversion function.
func Convert_kudo_AggregatedStatus_To_v1beta1_AggregatedStatus(in *kudo.AggregatedStatus, out *AggregatedStatus, s conversion.Scope) error {
	return autoConvert_kudo_AggregatedStatus_To_v1beta1_AggregatedStatus(in, out, s)
}

func autoConvert_v1beta1_DummyTaskSpec_To_kudo_DummyTaskSpec(in *DummyTaskSpec, out *kudo.DummyTaskSpec, s conversion.Scope) error {
	out.WantErr = in.WantErr
	out.Fatal = in.Fatal
	out.Done = in.Done
	return nil
}

// Convert_v1beta1_DummyTaskSpec_To_kudo_DummyTaskSpec is an autogenerated conversion function.
func Convert_v1beta1_DummyTaskSpec_To_kudo_DummyTaskSpec(in *DummyTaskSpec, out *kudo.DummyTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_DummyTaskSpec_To_kudo_DummyTaskSpec(in, out, s)
}

func autoConvert_kudo_DummyTaskSpec_To_v1beta1_DummyTaskSpec(in *kudo.DummyTaskSpec, out *DummyTaskSpec, s conversion.Scope) error {
	out.WantErr = in.WantErr
	out.Fatal = in.Fatal
	out.Done = in.Done
	return nil
}

// Convert_kudo_DummyTaskSpec_To_v1beta1_DummyTaskSpec is an autogenerated conversion function.
func Convert_kudo_DummyTaskSpec_To_v1beta1_DummyTaskSpec(in *kudo.DummyTaskSpec, out *DummyTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_DummyTaskSpec_To_v1beta1_DummyTaskSpec(in, out, s)
}

func autoConvert_v1beta1_Instance_To_kudo_Instance(in *Instance, out *kudo.Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_InstanceSpec_To_kudo_InstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_InstanceStatus_To_kudo_InstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Instance_To_kudo_Instance is an autogenerated conversion function.
func Convert_v1beta1_Instance_To_kudo_Instance(in *Instance, out *kudo.Instance, s conversion.Scope) error {
	return autoConvert_v1beta1_Instance_To_kudo_Instance(in, out, s)
}

func autoConvert_kudo_Instance_To_v1beta1_Instance(in *kudo.Instance, out *Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kudo_InstanceSpec_To_v1beta1_InstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kudo_InstanceStatus_To_v1beta1_InstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_Instance_To_v1beta1_Instance is an autogenerated conversion function.
func Convert_kudo_Instance_To_v1beta1_Instance(in *kudo.Instance, out *Instance, s conversion.Scope) error {
	return autoConvert_kudo_Instance_To_v1beta1_Instance(in, out, s)
}

func autoConvert_v1beta1_InstanceError_To_kudo_InstanceError(in *InstanceError, out *kudo.InstanceError, s conversion.Scope) error {
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Err, &out.Err, 0); err != nil {
		return err
	}
	out.EventName = (*string)(unsafe.Pointer(in.EventName))
	return nil
}

// Convert_v1beta1_InstanceError_To_kudo_InstanceError is an autogenerated conversion function.
func Convert_v1beta1_InstanceError_To_kudo_InstanceError(in *InstanceError, out *kudo.InstanceError, s conversion.Scope) error {
	return autoConvert_v1beta1_InstanceError_To_kudo_InstanceError(in, out, s)
}

func autoConvert_kudo_InstanceError_To_v1beta1_InstanceError(in *kudo.InstanceError, out *InstanceError, s conversion.Scope) error {
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Err, &out.Err, 0); err != nil {
		return err
	}
	out.EventName = (*string)(unsafe.Pointer(in.EventName))
	return nil
}

// Convert_kudo_InstanceError_To_v1beta1_InstanceError is an autogenerated conversion function.
func Convert_kudo_InstanceError_To_v1beta1_InstanceError(in *kudo.InstanceError, out *InstanceError, s conversion.Scope) error {
	return autoConvert_kudo_InstanceError_To_v1beta1_InstanceError(in, out, s)
}

func autoConvert_v1beta1_InstanceList_To_kudo_InstanceList(in *InstanceList, out *kudo.InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kudo.Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_InstanceList_To_kudo_InstanceList is an autogenerated conversion function.
func Convert_v1beta1_InstanceList_To_kudo_InstanceList(in *InstanceList, out *kudo.InstanceList, s conversion.Scope) error {
	return autoConvert_v1beta1_InstanceList_To_kudo_InstanceList(in, out, s)
}

func autoConvert_kudo_InstanceList_To_v1beta1_InstanceList(in *kudo.InstanceList, out *InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kudo_InstanceList_To_v1beta1_InstanceList is an autogenerated conversion function.
func Convert_kudo_InstanceList_To_v1beta1_InstanceList(in *kudo.InstanceList, out *InstanceList, s conversion.Scope) error {
	return autoConvert_kudo_InstanceList_To_v1beta1_InstanceList(in, out, s)
}

func autoConvert_v1beta1_InstanceSpec_To_kudo_InstanceSpec(in *InstanceSpec, out *kudo.InstanceSpec, s conversion.Scope) error {
	out.OperatorVersion = in.OperatorVersion
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	return nil
}

// Convert_v1beta1_InstanceSpec_To_kudo_InstanceSpec is an autogenerated conversion function.
func Convert_v1beta1_InstanceSpec_To_kudo_InstanceSpec(in *InstanceSpec, out *kudo.InstanceSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_InstanceSpec_To_kudo_InstanceSpec(in, out, s)
}

func autoConvert_kudo_InstanceSpec_To_v1beta1_InstanceSpec(in *kudo.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	out.OperatorVersion = in.OperatorVersion
	out.Parameters = *(*map[string]string)(unsafe.Pointer(&in.Parameters))
	return nil
}

// Convert_kudo_InstanceSpec_To_v1beta1_InstanceSpec is an autogenerated conversion function.
func Convert_kudo_InstanceSpec_To_v1beta1_InstanceSpec(in *kudo.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	return autoConvert_kudo_InstanceSpec_To_v1beta1_InstanceSpec(in, out, s)
}

func autoConvert_v1beta1_InstanceStatus_To_kudo_InstanceStatus(in *InstanceStatus, out *kudo.InstanceStatus, s conversion.Scope) error {
	out.PlanStatus = *(*map[string]kudo.PlanStatus)(unsafe.Pointer(&in.PlanStatus))
	if err := Convert_v1beta1_AggregatedStatus_To_kudo_AggregatedStatus(&in.AggregatedStatus, &out.AggregatedStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_InstanceStatus_To_kudo_InstanceStatus is an autogenerated conversion function.
func Convert_v1beta1_InstanceStatus_To_kudo_InstanceStatus(in *InstanceStatus, out *kudo.InstanceStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_InstanceStatus_To_kudo_InstanceStatus(in, out, s)
}

func autoConvert_kudo_InstanceStatus_To_v1beta1_InstanceStatus(in *kudo.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	out.PlanStatus = *(*map[string]PlanStatus)(unsafe.Pointer(&in.PlanStatus))
	if err := Convert_kudo_AggregatedStatus_To_v1beta1_AggregatedStatus(&in.AggregatedStatus, &out.AggregatedStatus, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_InstanceStatus_To_v1beta1_InstanceStatus is an autogenerated conversion function.
func Convert_kudo_InstanceStatus_To_v1beta1_InstanceStatus(in *kudo.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	return autoConvert_kudo_InstanceStatus_To_v1beta1_InstanceStatus(in, out, s)
}

func autoConvert_v1beta1_Maintainer_To_kudo_Maintainer(in *Maintainer, out *kudo.Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Email = in.Email
	return nil
}

// Convert_v1beta1_Maintainer_To_kudo_Maintainer is an autogenerated conversion function.
func Convert_v1beta1_Maintainer_To_kudo_Maintainer(in *Maintainer, out *kudo.Maintainer, s conversion.Scope) error {
	return autoConvert_v1beta1_Maintainer_To_kudo_Maintainer(in, out, s)
}

func autoConvert_kudo_Maintainer_To_v1beta1_Maintainer(in *kudo.Maintainer, out *Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Email = in.Email
	return nil
}

// Convert_kudo_Maintainer_To_v1beta1_Maintainer is an autogenerated conversion function.
func Convert_kudo_Maintainer_To_v1beta1_Maintainer(in *kudo.Maintainer, out *Maintainer, s conversion.Scope) error {
	return autoConvert_kudo_Maintainer_To_v1beta1_Maintainer(in, out, s)
}

func autoConvert_v1beta1_Operator_To_kudo_Operator(in *Operator, out *kudo.Operator, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OperatorSpec_To_kudo_OperatorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OperatorStatus_To_kudo_OperatorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Operator_To_kudo_Operator is an autogenerated conversion function.
func Convert_v1beta1_Operator_To_kudo_Operator(in *Operator, out *kudo.Operator, s conversion.Scope) error {
	return autoConvert_v1beta1_Operator_To_kudo_Operator(in, out, s)
}

func autoConvert_kudo_Operator_To_v1beta1_Operator(in *kudo.Operator, out *Operator, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kudo_OperatorSpec_To_v1beta1_OperatorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kudo_OperatorStatus_To_v1beta1_OperatorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_Operator_To_v1beta1_Operator is an autogenerated conversion function.
func Convert_kudo_Operator_To_v1beta1_Operator(in *kudo.Operator, out *Operator, s conversion.Scope) error {
	return autoConvert_kudo_Operator_To_v1beta1_Operator(in, out, s)
}

func autoConvert_v1beta1_OperatorDependency_To_kudo_OperatorDependency(in *OperatorDependency, out *kudo.OperatorDependency, s conversion.Scope) error {
	out.ReferenceName = in.ReferenceName
	out.ObjectReference = in.ObjectReference
	out.Version = in.Version
	return nil
}

// Convert_v1beta1_OperatorDependency_To_kudo_OperatorDependency is an autogenerated conversion function.
func Convert_v1beta1_OperatorDependency_To_kudo_OperatorDependency(in *OperatorDependency, out *kudo.OperatorDependency, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorDependency_To_kudo_OperatorDependency(in, out, s)
}

func autoConvert_kudo_OperatorDependency_To_v1beta1_OperatorDependency(in *kudo.OperatorDependency, out *OperatorDependency, s conversion.Scope) error {
	out.ReferenceName = in.ReferenceName
	out.ObjectReference = in.ObjectReference
	out.Version = in.Version
	return nil
}

// Convert_kudo_OperatorDependency_To_v1beta1_OperatorDependency is an autogenerated conversion function.
func Convert_kudo_OperatorDependency_To_v1beta1_OperatorDependency(in *kudo.OperatorDependency, out *OperatorDependency, s conversion.Scope) error {
	return autoConvert_kudo_OperatorDependency_To_v1beta1_OperatorDependency(in, out, s)
}

func autoConvert_v1beta1_OperatorList_To_kudo_OperatorList(in *OperatorList, out *kudo.OperatorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kudo.Operator)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_OperatorList_To_kudo_OperatorList is an autogenerated conversion function.
func Convert_v1beta1_OperatorList_To_kudo_OperatorList(in *OperatorList, out *kudo.OperatorList, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorList_To_kudo_OperatorList(in, out, s)
}

func autoConvert_kudo_OperatorList_To_v1beta1_OperatorList(in *kudo.OperatorList, out *OperatorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Operator)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kudo_OperatorList_To_v1beta1_OperatorList is an autogenerated conversion function.
func Convert_kudo_OperatorList_To_v1beta1_OperatorList(in *kudo.OperatorList, out *OperatorList, s conversion.Scope) error {
	return autoConvert_kudo_OperatorList_To_v1beta1_OperatorList(in, out, s)
}

func autoConvert_v1beta1_OperatorSpec_To_kudo_OperatorSpec(in *OperatorSpec, out *kudo.OperatorSpec, s conversion.Scope) error {
	out.Description = in.Description
	out.KudoVersion = in.KudoVersion
	out.KubernetesVersion = in.KubernetesVersion
	out.Maintainers = *(*[]*kudo.Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.URL = in.URL
	return nil
}

// Convert_v1beta1_OperatorSpec_To_kudo_OperatorSpec is an autogenerated conversion function.
func Convert_v1beta1_OperatorSpec_To_kudo_OperatorSpec(in *OperatorSpec, out *kudo.OperatorSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorSpec_To_kudo_OperatorSpec(in, out, s)
}

func autoConvert_kudo_OperatorSpec_To_v1beta1_OperatorSpec(in *kudo.OperatorSpec, out *OperatorSpec, s conversion.Scope) error {
	out.Description = in.Description
	out.KudoVersion = in.KudoVersion
	out.KubernetesVersion = in.KubernetesVersion
	out.Maintainers = *(*[]*Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.URL = in.URL
	return nil
}

// Convert_kudo_OperatorSpec_To_v1beta1_OperatorSpec is an autogenerated conversion function.
func Convert_kudo_OperatorSpec_To_v1beta1_OperatorSpec(in *kudo.OperatorSpec, out *OperatorSpec, s conversion.Scope) error {
	return autoConvert_kudo_OperatorSpec_To_v1beta1_OperatorSpec(in, out, s)
}

func autoConvert_v1beta1_OperatorStatus_To_kudo_OperatorStatus(in *OperatorStatus, out *kudo.OperatorStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_OperatorStatus_To_kudo_OperatorStatus is an autogenerated conversion function.
func Convert_v1beta1_OperatorStatus_To_kudo_OperatorStatus(in *OperatorStatus, out *kudo.OperatorStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorStatus_To_kudo_OperatorStatus(in, out, s)
}

func autoConvert_kudo_OperatorStatus_To_v1beta1_OperatorStatus(in *kudo.OperatorStatus, out *OperatorStatus, s conversion.Scope) error {
	return nil
}

// Convert_kudo_OperatorStatus_To_v1beta1_OperatorStatus is an autogenerated conversion function.
func Convert_kudo_OperatorStatus_To_v1beta1_OperatorStatus(in *kudo.OperatorStatus, out *OperatorStatus, s conversion.Scope) error {
	return autoConvert_kudo_OperatorStatus_To_v1beta1_OperatorStatus(in, out, s)
}

func autoConvert_v1beta1_OperatorVersion_To_kudo_OperatorVersion(in *OperatorVersion, out *kudo.OperatorVersion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_OperatorVersionSpec_To_kudo_OperatorVersionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_OperatorVersionStatus_To_kudo_OperatorVersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_OperatorVersion_To_kudo_OperatorVersion is an autogenerated conversion function.
func Convert_v1beta1_OperatorVersion_To_kudo_OperatorVersion(in *OperatorVersion, out *kudo.OperatorVersion, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorVersion_To_kudo_OperatorVersion(in, out, s)
}

func autoConvert_kudo_OperatorVersion_To_v1beta1_OperatorVersion(in *kudo.OperatorVersion, out *OperatorVersion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kudo_OperatorVersionSpec_To_v1beta1_OperatorVersionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kudo_OperatorVersionStatus_To_v1beta1_OperatorVersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_OperatorVersion_To_v1beta1_OperatorVersion is an autogenerated conversion function.
func Convert_kudo_OperatorVersion_To_v1beta1_OperatorVersion(in *kudo.OperatorVersion, out *OperatorVersion, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersion_To_v1beta1_OperatorVersion(in, out, s)
}

func autoConvert_v1beta1_OperatorVersionList_To_kudo_OperatorVersionList(in *OperatorVersionList, out *kudo.OperatorVersionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]kudo.OperatorVersion, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_OperatorVersion_To_kudo_OperatorVersion(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1beta1_OperatorVersionList_To_kudo_OperatorVersionList is an autogenerated conversion function.
func Convert_v1beta1_OperatorVersionList_To_kudo_OperatorVersionList(in *OperatorVersionList, out *kudo.OperatorVersionList, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorVersionList_To_kudo_OperatorVersionList(in, out, s)
}

func autoConvert_kudo_OperatorVersionList_To_v1beta1_OperatorVersionList(in *kudo.OperatorVersionList, out *OperatorVersionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatorVersion, len(*in))
		for i := range *in {
			if err := Convert_kudo_OperatorVersion_To_v1beta1_OperatorVersion(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_kudo_OperatorVersionList_To_v1beta1_OperatorVersionList is an autogenerated conversion function.
func Convert_kudo_OperatorVersionList_To_v1beta1_OperatorVersionList(in *kudo.OperatorVersionList, out *OperatorVersionList, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersionList_To_v1beta1_OperatorVersionList(in, out, s)
}

func autoConvert_v1beta1_OperatorVersionSpec_To_kudo_OperatorVersionSpec(in *OperatorVersionSpec, out *kudo.OperatorVersionSpec, s conversion.Scope) error {
	out.Operator = in.Operator
	out.Version = in.Version
	out.AppVersion = in.AppVersion
	out.Templates = *(*map[string]string)(unsafe.Pointer(&in.Templates))
	out.Tasks = *(*[]kudo.Task)(unsafe.Pointer(&in.Tasks))
	out.Parameters = *(*[]kudo.Parameter)(unsafe.Pointer(&in.Parameters))
	out.Plans = *(*map[string]kudo.Plan)(unsafe.Pointer(&in.Plans))
	out.ConnectionString = in.ConnectionString
	out.Dependencies = *(*[]kudo.OperatorDependency)(unsafe.Pointer(&in.Dependencies))
	if in.UpgradableFrom != nil {
		in, out := &in.UpgradableFrom, &out.UpgradableFrom
		*out = make([]kudo.OperatorVersion, len(*in))
		for i := range *in {
			// TODO: Inefficient conversion - can we improve it?
			if err := s.Convert(&(*in)[i], &(*out)[i], 0); err != nil {
				return err
			}
		}
	} else {
		out.UpgradableFrom = nil
	}
	return nil
}

// Convert_v1beta1_OperatorVersionSpec_To_kudo_OperatorVersionSpec is an autogenerated conversion function.
func Convert_v1beta1_OperatorVersionSpec_To_kudo_OperatorVersionSpec(in *OperatorVersionSpec, out *kudo.OperatorVersionSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorVersionSpec_To_kudo_OperatorVersionSpec(in, out, s)
}

func autoConvert_kudo_OperatorVersionSpec_To_v1beta1_OperatorVersionSpec(in *kudo.OperatorVersionSpec, out *OperatorVersionSpec, s conversion.Scope) error {
	out.Operator = in.Operator
	out.Version = in.Version
	out.AppVersion = in.AppVersion
	out.Templates = *(*map[string]string)(unsafe.Pointer(&in.Templates))
	out.Tasks = *(*[]Task)(unsafe.Pointer(&in.Tasks))
	out.Parameters = *(*[]Parameter)(unsafe.Pointer(&in.Parameters))
	out.Plans = *(*map[string]Plan)(unsafe.Pointer(&in.Plans))
	out.ConnectionString = in.ConnectionString
	out.Dependencies = *(*[]OperatorDependency)(unsafe.Pointer(&in.Dependencies))
	if in.UpgradableFrom != nil {
		in, out := &in.UpgradableFrom, &out.UpgradableFrom
		*out = make([]v1.ObjectReference, len(*in))
		for i := range *in {
			// TODO: Inefficient conversion - can we improve it?
			if err := s.Convert(&(*in)[i], &(*out)[i], 0); err != nil {
				return err
			}
		}
	} else {
		out.UpgradableFrom = nil
	}
	return nil
}

// Convert_kudo_OperatorVersionSpec_To_v1beta1_OperatorVersionSpec is an autogenerated conversion function.
func Convert_kudo_OperatorVersionSpec_To_v1beta1_OperatorVersionSpec(in *kudo.OperatorVersionSpec, out *OperatorVersionSpec, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersionSpec_To_v1beta1_OperatorVersionSpec(in, out, s)
}

func autoConvert_v1beta1_OperatorVersionStatus_To_kudo_OperatorVersionStatus(in *OperatorVersionStatus, out *kudo.OperatorVersionStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta1_OperatorVersionStatus_To_kudo_OperatorVersionStatus is an autogenerated conversion function.
func Convert_v1beta1_OperatorVersionStatus_To_kudo_OperatorVersionStatus(in *OperatorVersionStatus, out *kudo.OperatorVersionStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_OperatorVersionStatus_To_kudo_OperatorVersionStatus(in, out, s)
}

func autoConvert_kudo_OperatorVersionStatus_To_v1beta1_OperatorVersionStatus(in *kudo.OperatorVersionStatus, out *OperatorVersionStatus, s conversion.Scope) error {
	return nil
}

// Convert_kudo_OperatorVersionStatus_To_v1beta1_OperatorVersionStatus is an autogenerated conversion function.
func Convert_kudo_OperatorVersionStatus_To_v1beta1_OperatorVersionStatus(in *kudo.OperatorVersionStatus, out *OperatorVersionStatus, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersionStatus_To_v1beta1_OperatorVersionStatus(in, out, s)
}

func autoConvert_v1beta1_Parameter_To_kudo_Parameter(in *Parameter, out *kudo.Parameter, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Name = in.Name
	out.Description = in.Description
	out.Required = (*bool)(unsafe.Pointer(in.Required))
	out.Default = (*string)(unsafe.Pointer(in.Default))
	out.Trigger = in.Trigger
	return nil
}

// Convert_v1beta1_Parameter_To_kudo_Parameter is an autogenerated conversion function.
func Convert_v1beta1_Parameter_To_kudo_Parameter(in *Parameter, out *kudo.Parameter, s conversion.Scope) error {
	return autoConvert_v1beta1_Parameter_To_kudo_Parameter(in, out, s)
}

func autoConvert_kudo_Parameter_To_v1beta1_Parameter(in *kudo.Parameter, out *Parameter, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Name = in.Name
	out.Description = in.Description
	out.Required = (*bool)(unsafe.Pointer(in.Required))
	out.Default = (*string)(unsafe.Pointer(in.Default))
	out.Trigger = in.Trigger
	return nil
}

// Convert_kudo_Parameter_To_v1beta1_Parameter is an autogenerated conversion function.
func Convert_kudo_Parameter_To_v1beta1_Parameter(in *kudo.Parameter, out *Parameter, s conversion.Scope) error {
	return autoConvert_kudo_Parameter_To_v1beta1_Parameter(in, out, s)
}

func autoConvert_v1beta1_Phase_To_kudo_Phase(in *Phase, out *kudo.Phase, s conversion.Scope) error {
	out.Name = in.Name
	out.Strategy = kudo.Ordering(in.Strategy)
	out.Steps = *(*[]kudo.Step)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_v1beta1_Phase_To_kudo_Phase is an autogenerated conversion function.
func Convert_v1beta1_Phase_To_kudo_Phase(in *Phase, out *kudo.Phase, s conversion.Scope) error {
	return autoConvert_v1beta1_Phase_To_kudo_Phase(in, out, s)
}

func autoConvert_kudo_Phase_To_v1beta1_Phase(in *kudo.Phase, out *Phase, s conversion.Scope) error {
	out.Name = in.Name
	out.Strategy = Ordering(in.Strategy)
	out.Steps = *(*[]Step)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_kudo_Phase_To_v1beta1_Phase is an autogenerated conversion function.
func Convert_kudo_Phase_To_v1beta1_Phase(in *kudo.Phase, out *Phase, s conversion.Scope) error {
	return autoConvert_kudo_Phase_To_v1beta1_Phase(in, out, s)
}

func autoConvert_v1beta1_PhaseStatus_To_kudo_PhaseStatus(in *PhaseStatus, out *kudo.PhaseStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = kudo.ExecutionStatus(in.Status)
	out.Message = in.Message
	out.Steps = *(*[]kudo.StepStatus)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_v1beta1_PhaseStatus_To_kudo_PhaseStatus is an autogenerated conversion function.
func Convert_v1beta1_PhaseStatus_To_kudo_PhaseStatus(in *PhaseStatus, out *kudo.PhaseStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_PhaseStatus_To_kudo_PhaseStatus(in, out, s)
}

func autoConvert_kudo_PhaseStatus_To_v1beta1_PhaseStatus(in *kudo.PhaseStatus, out *PhaseStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = ExecutionStatus(in.Status)
	out.Message = in.Message
	out.Steps = *(*[]StepStatus)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_kudo_PhaseStatus_To_v1beta1_PhaseStatus is an autogenerated conversion function.
func Convert_kudo_PhaseStatus_To_v1beta1_PhaseStatus(in *kudo.PhaseStatus, out *PhaseStatus, s conversion.Scope) error {
	return autoConvert_kudo_PhaseStatus_To_v1beta1_PhaseStatus(in, out, s)
}

func autoConvert_v1beta1_PipeSpec_To_kudo_PipeSpec(in *PipeSpec, out *kudo.PipeSpec, s conversion.Scope) error {
	out.File = in.File
	out.Kind = in.Kind
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_PipeSpec_To_kudo_PipeSpec is an autogenerated conversion function.
func Convert_v1beta1_PipeSpec_To_kudo_PipeSpec(in *PipeSpec, out *kudo.PipeSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PipeSpec_To_kudo_PipeSpec(in, out, s)
}

func autoConvert_kudo_PipeSpec_To_v1beta1_PipeSpec(in *kudo.PipeSpec, out *PipeSpec, s conversion.Scope) error {
	out.File = in.File
	out.Kind = in.Kind
	out.Key = in.Key
	return nil
}

// Convert_kudo_PipeSpec_To_v1beta1_PipeSpec is an autogenerated conversion function.
func Convert_kudo_PipeSpec_To_v1beta1_PipeSpec(in *kudo.PipeSpec, out *PipeSpec, s conversion.Scope) error {
	return autoConvert_kudo_PipeSpec_To_v1beta1_PipeSpec(in, out, s)
}

func autoConvert_v1beta1_PipeTaskSpec_To_kudo_PipeTaskSpec(in *PipeTaskSpec, out *kudo.PipeTaskSpec, s conversion.Scope) error {
	out.Pod = in.Pod
	out.Pipe = *(*[]kudo.PipeSpec)(unsafe.Pointer(&in.Pipe))
	return nil
}

// Convert_v1beta1_PipeTaskSpec_To_kudo_PipeTaskSpec is an autogenerated conversion function.
func Convert_v1beta1_PipeTaskSpec_To_kudo_PipeTaskSpec(in *PipeTaskSpec, out *kudo.PipeTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_PipeTaskSpec_To_kudo_PipeTaskSpec(in, out, s)
}

func autoConvert_kudo_PipeTaskSpec_To_v1beta1_PipeTaskSpec(in *kudo.PipeTaskSpec, out *PipeTaskSpec, s conversion.Scope) error {
	out.Pod = in.Pod
	out.Pipe = *(*[]PipeSpec)(unsafe.Pointer(&in.Pipe))
	return nil
}

// Convert_kudo_PipeTaskSpec_To_v1beta1_PipeTaskSpec is an autogenerated conversion function.
func Convert_kudo_PipeTaskSpec_To_v1beta1_PipeTaskSpec(in *kudo.PipeTaskSpec, out *PipeTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_PipeTaskSpec_To_v1beta1_PipeTaskSpec(in, out, s)
}

func autoConvert_v1beta1_Plan_To_kudo_Plan(in *Plan, out *kudo.Plan, s conversion.Scope) error {
	out.Strategy = kudo.Ordering(in.Strategy)
	out.Phases = *(*[]kudo.Phase)(unsafe.Pointer(&in.Phases))
	return nil
}

// Convert_v1beta1_Plan_To_kudo_Plan is an autogenerated conversion function.
func Convert_v1beta1_Plan_To_kudo_Plan(in *Plan, out *kudo.Plan, s conversion.Scope) error {
	return autoConvert_v1beta1_Plan_To_kudo_Plan(in, out, s)
}

func autoConvert_kudo_Plan_To_v1beta1_Plan(in *kudo.Plan, out *Plan, s conversion.Scope) error {
	out.Strategy = Ordering(in.Strategy)
	out.Phases = *(*[]Phase)(unsafe.Pointer(&in.Phases))
	return nil
}

// Convert_kudo_Plan_To_v1beta1_Plan is an autogenerated conversion function.
func Convert_kudo_Plan_To_v1beta1_Plan(in *kudo.Plan, out *Plan, s conversion.Scope) error {
	return autoConvert_kudo_Plan_To_v1beta1_Plan(in, out, s)
}

func autoConvert_v1beta1_PlanStatus_To_kudo_PlanStatus(in *PlanStatus, out *kudo.PlanStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = kudo.ExecutionStatus(in.Status)
	out.Message = in.Message
	out.LastFinishedRun = in.LastFinishedRun
	out.Phases = *(*[]kudo.PhaseStatus)(unsafe.Pointer(&in.Phases))
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_v1beta1_PlanStatus_To_kudo_PlanStatus is an autogenerated conversion function.
func Convert_v1beta1_PlanStatus_To_kudo_PlanStatus(in *PlanStatus, out *kudo.PlanStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_PlanStatus_To_kudo_PlanStatus(in, out, s)
}

func autoConvert_kudo_PlanStatus_To_v1beta1_PlanStatus(in *kudo.PlanStatus, out *PlanStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = ExecutionStatus(in.Status)
	out.Message = in.Message
	out.LastFinishedRun = in.LastFinishedRun
	out.Phases = *(*[]PhaseStatus)(unsafe.Pointer(&in.Phases))
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_kudo_PlanStatus_To_v1beta1_PlanStatus is an autogenerated conversion function.
func Convert_kudo_PlanStatus_To_v1beta1_PlanStatus(in *kudo.PlanStatus, out *PlanStatus, s conversion.Scope) error {
	return autoConvert_kudo_PlanStatus_To_v1beta1_PlanStatus(in, out, s)
}

func autoConvert_v1beta1_ResourceTaskSpec_To_kudo_ResourceTaskSpec(in *ResourceTaskSpec, out *kudo.ResourceTaskSpec, s conversion.Scope) error {
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1beta1_ResourceTaskSpec_To_kudo_ResourceTaskSpec is an autogenerated conversion function.
func Convert_v1beta1_ResourceTaskSpec_To_kudo_ResourceTaskSpec(in *ResourceTaskSpec, out *kudo.ResourceTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceTaskSpec_To_kudo_ResourceTaskSpec(in, out, s)
}

func autoConvert_kudo_ResourceTaskSpec_To_v1beta1_ResourceTaskSpec(in *kudo.ResourceTaskSpec, out *ResourceTaskSpec, s conversion.Scope) error {
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_kudo_ResourceTaskSpec_To_v1beta1_ResourceTaskSpec is an autogenerated conversion function.
func Convert_kudo_ResourceTaskSpec_To_v1beta1_ResourceTaskSpec(in *kudo.ResourceTaskSpec, out *ResourceTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_ResourceTaskSpec_To_v1beta1_ResourceTaskSpec(in, out, s)
}

func autoConvert_v1beta1_Step_To_kudo_Step(in *Step, out *kudo.Step, s conversion.Scope) error {
	out.Name = in.Name
	out.Tasks = *(*[]string)(unsafe.Pointer(&in.Tasks))
	return nil
}

// Convert_v1beta1_Step_To_kudo_Step is an autogenerated conversion function.
func Convert_v1beta1_Step_To_kudo_Step(in *Step, out *kudo.Step, s conversion.Scope) error {
	return autoConvert_v1beta1_Step_To_kudo_Step(in, out, s)
}

func autoConvert_kudo_Step_To_v1beta1_Step(in *kudo.Step, out *Step, s conversion.Scope) error {
	out.Name = in.Name
	out.Tasks = *(*[]string)(unsafe.Pointer(&in.Tasks))
	return nil
}

// Convert_kudo_Step_To_v1beta1_Step is an autogenerated conversion function.
func Convert_kudo_Step_To_v1beta1_Step(in *kudo.Step, out *Step, s conversion.Scope) error {
	return autoConvert_kudo_Step_To_v1beta1_Step(in, out, s)
}

func autoConvert_v1beta1_StepStatus_To_kudo_StepStatus(in *StepStatus, out *kudo.StepStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Message = in.Message
	out.Status = kudo.ExecutionStatus(in.Status)
	return nil
}

// Convert_v1beta1_StepStatus_To_kudo_StepStatus is an autogenerated conversion function.
func Convert_v1beta1_StepStatus_To_kudo_StepStatus(in *StepStatus, out *kudo.StepStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_StepStatus_To_kudo_StepStatus(in, out, s)
}

func autoConvert_kudo_StepStatus_To_v1beta1_StepStatus(in *kudo.StepStatus, out *StepStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Message = in.Message
	out.Status = ExecutionStatus(in.Status)
	return nil
}

// Convert_kudo_StepStatus_To_v1beta1_StepStatus is an autogenerated conversion function.
func Convert_kudo_StepStatus_To_v1beta1_StepStatus(in *kudo.StepStatus, out *StepStatus, s conversion.Scope) error {
	return autoConvert_kudo_StepStatus_To_v1beta1_StepStatus(in, out, s)
}

func autoConvert_v1beta1_Task_To_kudo_Task(in *Task, out *kudo.Task, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	if err := Convert_v1beta1_TaskSpec_To_kudo_TaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Task_To_kudo_Task is an autogenerated conversion function.
func Convert_v1beta1_Task_To_kudo_Task(in *Task, out *kudo.Task, s conversion.Scope) error {
	return autoConvert_v1beta1_Task_To_kudo_Task(in, out, s)
}

func autoConvert_kudo_Task_To_v1beta1_Task(in *kudo.Task, out *Task, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	if err := Convert_kudo_TaskSpec_To_v1beta1_TaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_Task_To_v1beta1_Task is an autogenerated conversion function.
func Convert_kudo_Task_To_v1beta1_Task(in *kudo.Task, out *Task, s conversion.Scope) error {
	return autoConvert_kudo_Task_To_v1beta1_Task(in, out, s)
}

func autoConvert_v1beta1_TaskSpec_To_kudo_TaskSpec(in *TaskSpec, out *kudo.TaskSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_ResourceTaskSpec_To_kudo_ResourceTaskSpec(&in.ResourceTaskSpec, &out.ResourceTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_DummyTaskSpec_To_kudo_DummyTaskSpec(&in.DummyTaskSpec, &out.DummyTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_PipeTaskSpec_To_kudo_PipeTaskSpec(&in.PipeTaskSpec, &out.PipeTaskSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TaskSpec_To_kudo_TaskSpec is an autogenerated conversion function.
func Convert_v1beta1_TaskSpec_To_kudo_TaskSpec(in *TaskSpec, out *kudo.TaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_TaskSpec_To_kudo_TaskSpec(in, out, s)
}

func autoConvert_kudo_TaskSpec_To_v1beta1_TaskSpec(in *kudo.TaskSpec, out *TaskSpec, s conversion.Scope) error {
	if err := Convert_kudo_ResourceTaskSpec_To_v1beta1_ResourceTaskSpec(&in.ResourceTaskSpec, &out.ResourceTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_kudo_DummyTaskSpec_To_v1beta1_DummyTaskSpec(&in.DummyTaskSpec, &out.DummyTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_kudo_PipeTaskSpec_To_v1beta1_PipeTaskSpec(&in.PipeTaskSpec, &out.PipeTaskSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_TaskSpec_To_v1beta1_TaskSpec is an autogenerated conversion function.
func Convert_kudo_TaskSpec_To_v1beta1_TaskSpec(in *kudo.TaskSpec, out *TaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_TaskSpec_To_v1beta1_TaskSpec(in, out, s)
}
