/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kudobuilder/kudo/pkg/apis/kudo/v1alpha1"
	scheme "github.com/kudobuilder/kudo/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FrameworkVersionsGetter has a method to return a FrameworkVersionInterface.
// A group's client should implement this interface.
type FrameworkVersionsGetter interface {
	FrameworkVersions(namespace string) FrameworkVersionInterface
}

// FrameworkVersionInterface has methods to work with FrameworkVersion resources.
type FrameworkVersionInterface interface {
	Create(*v1alpha1.FrameworkVersion) (*v1alpha1.FrameworkVersion, error)
	Update(*v1alpha1.FrameworkVersion) (*v1alpha1.FrameworkVersion, error)
	UpdateStatus(*v1alpha1.FrameworkVersion) (*v1alpha1.FrameworkVersion, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.FrameworkVersion, error)
	List(opts v1.ListOptions) (*v1alpha1.FrameworkVersionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FrameworkVersion, err error)
	FrameworkVersionExpansion
}

// frameworkVersions implements FrameworkVersionInterface
type frameworkVersions struct {
	client rest.Interface
	ns     string
}

// newFrameworkVersions returns a FrameworkVersions
func newFrameworkVersions(c *KudoV1alpha1Client, namespace string) *frameworkVersions {
	return &frameworkVersions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the frameworkVersion, and returns the corresponding frameworkVersion object, and an error if there is any.
func (c *frameworkVersions) Get(name string, options v1.GetOptions) (result *v1alpha1.FrameworkVersion, err error) {
	result = &v1alpha1.FrameworkVersion{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("frameworkversions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of FrameworkVersions that match those selectors.
func (c *frameworkVersions) List(opts v1.ListOptions) (result *v1alpha1.FrameworkVersionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FrameworkVersionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("frameworkversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested frameworkVersions.
func (c *frameworkVersions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("frameworkversions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a frameworkVersion and creates it.  Returns the server's representation of the frameworkVersion, and an error, if there is any.
func (c *frameworkVersions) Create(frameworkVersion *v1alpha1.FrameworkVersion) (result *v1alpha1.FrameworkVersion, err error) {
	result = &v1alpha1.FrameworkVersion{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("frameworkversions").
		Body(frameworkVersion).
		Do().
		Into(result)
	return
}

// Update takes the representation of a frameworkVersion and updates it. Returns the server's representation of the frameworkVersion, and an error, if there is any.
func (c *frameworkVersions) Update(frameworkVersion *v1alpha1.FrameworkVersion) (result *v1alpha1.FrameworkVersion, err error) {
	result = &v1alpha1.FrameworkVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("frameworkversions").
		Name(frameworkVersion.Name).
		Body(frameworkVersion).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *frameworkVersions) UpdateStatus(frameworkVersion *v1alpha1.FrameworkVersion) (result *v1alpha1.FrameworkVersion, err error) {
	result = &v1alpha1.FrameworkVersion{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("frameworkversions").
		Name(frameworkVersion.Name).
		SubResource("status").
		Body(frameworkVersion).
		Do().
		Into(result)
	return
}

// Delete takes name of the frameworkVersion and deletes it. Returns an error if one occurs.
func (c *frameworkVersions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("frameworkversions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *frameworkVersions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("frameworkversions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched frameworkVersion.
func (c *frameworkVersions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.FrameworkVersion, err error) {
	result = &v1alpha1.FrameworkVersion{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("frameworkversions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
