apiVersion: kudo.k8s.io/v1alpha1
kind: OperatorVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: zookeeper-1.0
  namespace: default
spec:
  operator:
    name: zookeeper
    kind: Operator
  # Add fields here
  version: "1.0"
  parameters:
  - name: memory
    description: Amount of memory to provide to Zookeeper pods
    default: "1Gi"
  - name: cpus
    description: Amount of cpu to provide to Zookeeper pods
    default: "0.25"
  templates:
    services.yaml: |
      apiVersion: v1
      kind: Service
      metadata:
        name: hs
        namespace: {{ .Namespace }}
        labels:
          app: zookeeper
          zookeeper: {{ .Name }}
      spec:
        ports:
          - port: 2888
            name: server
          - port: 3888
            name: leader-election
        clusterIP: None
        selector:
          app: zookeeper
          zookeeper: {{ .Name }}
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: cs
        namespace: {{ .Namespace }}
        labels:
          app: zookeeper
          zookeeper: {{ .Name }}
      spec:
        ports:
          - port: 2181
            name: client
        selector:
          app: zookeeper
          zookeeper: {{ .Name }}
    pdb.yaml: |
      apiVersion: policy/v1beta1
      kind: PodDisruptionBudget
      metadata:
        name: {{ .Name }}-pdb
        namespace: {{ .Namespace }}
        labels:
          app: zookeeper
          zookeeper: {{ .Name }}
      spec:
        selector:
          matchLabels:
            app: zookeeper
            zookeeper: {{ .Name }}
        maxUnavailable: 1
    statefulset.yaml: |
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: {{ .Name }}
        namespace: {{ .Namespace }}
      spec:
        selector:
          matchLabels:
            app: zookeeper
            zookeeper: {{ .Name }}
        serviceName: {{ .Name }}-hs
        replicas: 3
        updateStrategy:
          type: RollingUpdate
        podManagementPolicy: Parallel
        template:
          metadata:
            labels:
              app: zookeeper
              zookeeper: {{ .Name }}
          spec:
            containers:
              - name: kubernetes-zookeeper
                imagePullPolicy: Always
                image: "k8s.gcr.io/kubernetes-zookeeper:1.0-3.4.10"
                resources:
                  requests:
                    memory: "{{ .Params.memory }}"
                    cpu: "{{ .Params.cpus }}"
                ports:
                  - containerPort: 2181
                    name: client
                  - containerPort: 2888
                    name: server
                  - containerPort: 3888
                    name: leader-election
                command:
                  - sh
                  - -c
                  - "start-zookeeper \
                    --servers=3 \
                    --data_dir=/var/lib/zookeeper/data \
                    --data_log_dir=/var/lib/zookeeper/data/log \
                    --conf_dir=/opt/zookeeper/conf \
                    --client_port=2181 \
                    --election_port=3888 \
                    --server_port=2888 \
                    --tick_time=2000 \
                    --init_limit=10 \
                    --sync_limit=5 \
                    --heap=512M \
                    --max_client_cnxns=60 \
                    --snap_retain_count=3 \
                    --purge_interval=12 \
                    --max_session_timeout=40000 \
                    --min_session_timeout=4000 \
                    --log_level=INFO"
                volumeMounts:
                  - name: datadir
                    mountPath: /var/lib/zookeeper
            securityContext:
              runAsUser: 1000
              fsGroup: 1000
        volumeClaimTemplates:
          - metadata:
              name: datadir
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
    validation.yaml: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: zookeeper-validation
      spec:
        template:
          metadata:
            name: "validation"
          spec:
            restartPolicy: Never
            containers:
            - name: kubernetes-zookeeper
              imagePullPolicy: Always
              image: "k8s.gcr.io/kubernetes-zookeeper:1.0-3.4.10"
              env:
              - name: CONN
                value: zk-zk-0.zk-hs:2181,zk-zk-1.zk-hs:2181,zk-zk-2.zk-hs:2181
              resources:
                requests:
                  memory: "{{ .Params.memory }}"
                  cpu: "{{ .Params.cpus }}"
                command:
                  - sh
                  - -c
                  - "/opt/zookeeper/bin/zkCLI.sh \
                    --server $CONN \
                    ls /"
  tasks:
    infra:
      resources:
      - services.yaml
      - pdb.yaml
    app:
      resources:
      - statefulset.yaml
    validation:
      resources:
      - validation.yaml
  plans:
    deploy:
      strategy: serial
      phases:
        - name: zookeeper
          strategy: parallel
          steps:
            - name: everything
              tasks:
              - infra
              - app
    validation:
      strategy: serial
      phases:
      - name: connection
        strategy: parallel
        steps:
        - name: connection
          tasks:
          - validation
              
