// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1beta2

import (
	unsafe "unsafe"

	kudo "github.com/kudobuilder/kudo/pkg/apis/kudo"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DummyTaskSpec)(nil), (*kudo.DummyTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_DummyTaskSpec_To_kudo_DummyTaskSpec(a.(*DummyTaskSpec), b.(*kudo.DummyTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.DummyTaskSpec)(nil), (*DummyTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_DummyTaskSpec_To_v1beta2_DummyTaskSpec(a.(*kudo.DummyTaskSpec), b.(*DummyTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Instance)(nil), (*kudo.Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Instance_To_kudo_Instance(a.(*Instance), b.(*kudo.Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Instance)(nil), (*Instance)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Instance_To_v1beta2_Instance(a.(*kudo.Instance), b.(*Instance), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceList)(nil), (*kudo.InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_InstanceList_To_kudo_InstanceList(a.(*InstanceList), b.(*kudo.InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceList)(nil), (*InstanceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceList_To_v1beta2_InstanceList(a.(*kudo.InstanceList), b.(*InstanceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceSpec)(nil), (*kudo.InstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_InstanceSpec_To_kudo_InstanceSpec(a.(*InstanceSpec), b.(*kudo.InstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceSpec)(nil), (*InstanceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceSpec_To_v1beta2_InstanceSpec(a.(*kudo.InstanceSpec), b.(*InstanceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstanceStatus)(nil), (*kudo.InstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_InstanceStatus_To_kudo_InstanceStatus(a.(*InstanceStatus), b.(*kudo.InstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.InstanceStatus)(nil), (*InstanceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_InstanceStatus_To_v1beta2_InstanceStatus(a.(*kudo.InstanceStatus), b.(*InstanceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KudoOperatorTaskSpec)(nil), (*kudo.KudoOperatorTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_KudoOperatorTaskSpec_To_kudo_KudoOperatorTaskSpec(a.(*KudoOperatorTaskSpec), b.(*kudo.KudoOperatorTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.KudoOperatorTaskSpec)(nil), (*KudoOperatorTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_KudoOperatorTaskSpec_To_v1beta2_KudoOperatorTaskSpec(a.(*kudo.KudoOperatorTaskSpec), b.(*KudoOperatorTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Maintainer)(nil), (*kudo.Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Maintainer_To_kudo_Maintainer(a.(*Maintainer), b.(*kudo.Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Maintainer)(nil), (*Maintainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Maintainer_To_v1beta2_Maintainer(a.(*kudo.Maintainer), b.(*Maintainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Operator)(nil), (*kudo.Operator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Operator_To_kudo_Operator(a.(*Operator), b.(*kudo.Operator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Operator)(nil), (*Operator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Operator_To_v1beta2_Operator(a.(*kudo.Operator), b.(*Operator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorList)(nil), (*kudo.OperatorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorList_To_kudo_OperatorList(a.(*OperatorList), b.(*kudo.OperatorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorList)(nil), (*OperatorList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorList_To_v1beta2_OperatorList(a.(*kudo.OperatorList), b.(*OperatorList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorSpec)(nil), (*kudo.OperatorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorSpec_To_kudo_OperatorSpec(a.(*OperatorSpec), b.(*kudo.OperatorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorSpec)(nil), (*OperatorSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorSpec_To_v1beta2_OperatorSpec(a.(*kudo.OperatorSpec), b.(*OperatorSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorStatus)(nil), (*kudo.OperatorStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorStatus_To_kudo_OperatorStatus(a.(*OperatorStatus), b.(*kudo.OperatorStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorStatus)(nil), (*OperatorStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorStatus_To_v1beta2_OperatorStatus(a.(*kudo.OperatorStatus), b.(*OperatorStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersion)(nil), (*kudo.OperatorVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorVersion_To_kudo_OperatorVersion(a.(*OperatorVersion), b.(*kudo.OperatorVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersion)(nil), (*OperatorVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersion_To_v1beta2_OperatorVersion(a.(*kudo.OperatorVersion), b.(*OperatorVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersionList)(nil), (*kudo.OperatorVersionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorVersionList_To_kudo_OperatorVersionList(a.(*OperatorVersionList), b.(*kudo.OperatorVersionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersionList)(nil), (*OperatorVersionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersionList_To_v1beta2_OperatorVersionList(a.(*kudo.OperatorVersionList), b.(*OperatorVersionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersionSpec)(nil), (*kudo.OperatorVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorVersionSpec_To_kudo_OperatorVersionSpec(a.(*OperatorVersionSpec), b.(*kudo.OperatorVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersionSpec)(nil), (*OperatorVersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersionSpec_To_v1beta2_OperatorVersionSpec(a.(*kudo.OperatorVersionSpec), b.(*OperatorVersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorVersionStatus)(nil), (*kudo.OperatorVersionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_OperatorVersionStatus_To_kudo_OperatorVersionStatus(a.(*OperatorVersionStatus), b.(*kudo.OperatorVersionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.OperatorVersionStatus)(nil), (*OperatorVersionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_OperatorVersionStatus_To_v1beta2_OperatorVersionStatus(a.(*kudo.OperatorVersionStatus), b.(*OperatorVersionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Parameter)(nil), (*kudo.Parameter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Parameter_To_kudo_Parameter(a.(*Parameter), b.(*kudo.Parameter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Parameter)(nil), (*Parameter)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Parameter_To_v1beta2_Parameter(a.(*kudo.Parameter), b.(*Parameter), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Phase)(nil), (*kudo.Phase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Phase_To_kudo_Phase(a.(*Phase), b.(*kudo.Phase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Phase)(nil), (*Phase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Phase_To_v1beta2_Phase(a.(*kudo.Phase), b.(*Phase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PhaseStatus)(nil), (*kudo.PhaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PhaseStatus_To_kudo_PhaseStatus(a.(*PhaseStatus), b.(*kudo.PhaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PhaseStatus)(nil), (*PhaseStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PhaseStatus_To_v1beta2_PhaseStatus(a.(*kudo.PhaseStatus), b.(*PhaseStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PipeSpec)(nil), (*kudo.PipeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PipeSpec_To_kudo_PipeSpec(a.(*PipeSpec), b.(*kudo.PipeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PipeSpec)(nil), (*PipeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PipeSpec_To_v1beta2_PipeSpec(a.(*kudo.PipeSpec), b.(*PipeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PipeTaskSpec)(nil), (*kudo.PipeTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PipeTaskSpec_To_kudo_PipeTaskSpec(a.(*PipeTaskSpec), b.(*kudo.PipeTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PipeTaskSpec)(nil), (*PipeTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PipeTaskSpec_To_v1beta2_PipeTaskSpec(a.(*kudo.PipeTaskSpec), b.(*PipeTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Plan)(nil), (*kudo.Plan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Plan_To_kudo_Plan(a.(*Plan), b.(*kudo.Plan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Plan)(nil), (*Plan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Plan_To_v1beta2_Plan(a.(*kudo.Plan), b.(*Plan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlanExecution)(nil), (*kudo.PlanExecution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PlanExecution_To_kudo_PlanExecution(a.(*PlanExecution), b.(*kudo.PlanExecution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PlanExecution)(nil), (*PlanExecution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PlanExecution_To_v1beta2_PlanExecution(a.(*kudo.PlanExecution), b.(*PlanExecution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlanStatus)(nil), (*kudo.PlanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PlanStatus_To_kudo_PlanStatus(a.(*PlanStatus), b.(*kudo.PlanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.PlanStatus)(nil), (*PlanStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_PlanStatus_To_v1beta2_PlanStatus(a.(*kudo.PlanStatus), b.(*PlanStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceTaskSpec)(nil), (*kudo.ResourceTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ResourceTaskSpec_To_kudo_ResourceTaskSpec(a.(*ResourceTaskSpec), b.(*kudo.ResourceTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.ResourceTaskSpec)(nil), (*ResourceTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_ResourceTaskSpec_To_v1beta2_ResourceTaskSpec(a.(*kudo.ResourceTaskSpec), b.(*ResourceTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Step)(nil), (*kudo.Step)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Step_To_kudo_Step(a.(*Step), b.(*kudo.Step), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Step)(nil), (*Step)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Step_To_v1beta2_Step(a.(*kudo.Step), b.(*Step), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StepStatus)(nil), (*kudo.StepStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_StepStatus_To_kudo_StepStatus(a.(*StepStatus), b.(*kudo.StepStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.StepStatus)(nil), (*StepStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_StepStatus_To_v1beta2_StepStatus(a.(*kudo.StepStatus), b.(*StepStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Task)(nil), (*kudo.Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Task_To_kudo_Task(a.(*Task), b.(*kudo.Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.Task)(nil), (*Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_Task_To_v1beta2_Task(a.(*kudo.Task), b.(*Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskSpec)(nil), (*kudo.TaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_TaskSpec_To_kudo_TaskSpec(a.(*TaskSpec), b.(*kudo.TaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.TaskSpec)(nil), (*TaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_TaskSpec_To_v1beta2_TaskSpec(a.(*kudo.TaskSpec), b.(*TaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ToggleTaskSpec)(nil), (*kudo.ToggleTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_ToggleTaskSpec_To_kudo_ToggleTaskSpec(a.(*ToggleTaskSpec), b.(*kudo.ToggleTaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kudo.ToggleTaskSpec)(nil), (*ToggleTaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kudo_ToggleTaskSpec_To_v1beta2_ToggleTaskSpec(a.(*kudo.ToggleTaskSpec), b.(*ToggleTaskSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta2_DummyTaskSpec_To_kudo_DummyTaskSpec(in *DummyTaskSpec, out *kudo.DummyTaskSpec, s conversion.Scope) error {
	out.WantErr = in.WantErr
	out.Fatal = in.Fatal
	out.Done = in.Done
	return nil
}

// Convert_v1beta2_DummyTaskSpec_To_kudo_DummyTaskSpec is an autogenerated conversion function.
func Convert_v1beta2_DummyTaskSpec_To_kudo_DummyTaskSpec(in *DummyTaskSpec, out *kudo.DummyTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_DummyTaskSpec_To_kudo_DummyTaskSpec(in, out, s)
}

func autoConvert_kudo_DummyTaskSpec_To_v1beta2_DummyTaskSpec(in *kudo.DummyTaskSpec, out *DummyTaskSpec, s conversion.Scope) error {
	out.WantErr = in.WantErr
	out.Fatal = in.Fatal
	out.Done = in.Done
	return nil
}

// Convert_kudo_DummyTaskSpec_To_v1beta2_DummyTaskSpec is an autogenerated conversion function.
func Convert_kudo_DummyTaskSpec_To_v1beta2_DummyTaskSpec(in *kudo.DummyTaskSpec, out *DummyTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_DummyTaskSpec_To_v1beta2_DummyTaskSpec(in, out, s)
}

func autoConvert_v1beta2_Instance_To_kudo_Instance(in *Instance, out *kudo.Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_InstanceSpec_To_kudo_InstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_InstanceStatus_To_kudo_InstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_Instance_To_kudo_Instance is an autogenerated conversion function.
func Convert_v1beta2_Instance_To_kudo_Instance(in *Instance, out *kudo.Instance, s conversion.Scope) error {
	return autoConvert_v1beta2_Instance_To_kudo_Instance(in, out, s)
}

func autoConvert_kudo_Instance_To_v1beta2_Instance(in *kudo.Instance, out *Instance, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kudo_InstanceSpec_To_v1beta2_InstanceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kudo_InstanceStatus_To_v1beta2_InstanceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_Instance_To_v1beta2_Instance is an autogenerated conversion function.
func Convert_kudo_Instance_To_v1beta2_Instance(in *kudo.Instance, out *Instance, s conversion.Scope) error {
	return autoConvert_kudo_Instance_To_v1beta2_Instance(in, out, s)
}

func autoConvert_v1beta2_InstanceList_To_kudo_InstanceList(in *InstanceList, out *kudo.InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kudo.Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_InstanceList_To_kudo_InstanceList is an autogenerated conversion function.
func Convert_v1beta2_InstanceList_To_kudo_InstanceList(in *InstanceList, out *kudo.InstanceList, s conversion.Scope) error {
	return autoConvert_v1beta2_InstanceList_To_kudo_InstanceList(in, out, s)
}

func autoConvert_kudo_InstanceList_To_v1beta2_InstanceList(in *kudo.InstanceList, out *InstanceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Instance)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kudo_InstanceList_To_v1beta2_InstanceList is an autogenerated conversion function.
func Convert_kudo_InstanceList_To_v1beta2_InstanceList(in *kudo.InstanceList, out *InstanceList, s conversion.Scope) error {
	return autoConvert_kudo_InstanceList_To_v1beta2_InstanceList(in, out, s)
}

func autoConvert_v1beta2_InstanceSpec_To_kudo_InstanceSpec(in *InstanceSpec, out *kudo.InstanceSpec, s conversion.Scope) error {
	out.OperatorVersion = in.OperatorVersion
	out.Parameters = in.Parameters
	if err := Convert_v1beta2_PlanExecution_To_kudo_PlanExecution(&in.PlanExecution, &out.PlanExecution, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_InstanceSpec_To_kudo_InstanceSpec is an autogenerated conversion function.
func Convert_v1beta2_InstanceSpec_To_kudo_InstanceSpec(in *InstanceSpec, out *kudo.InstanceSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_InstanceSpec_To_kudo_InstanceSpec(in, out, s)
}

func autoConvert_kudo_InstanceSpec_To_v1beta2_InstanceSpec(in *kudo.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	out.OperatorVersion = in.OperatorVersion
	out.Parameters = in.Parameters
	if err := Convert_kudo_PlanExecution_To_v1beta2_PlanExecution(&in.PlanExecution, &out.PlanExecution, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_InstanceSpec_To_v1beta2_InstanceSpec is an autogenerated conversion function.
func Convert_kudo_InstanceSpec_To_v1beta2_InstanceSpec(in *kudo.InstanceSpec, out *InstanceSpec, s conversion.Scope) error {
	return autoConvert_kudo_InstanceSpec_To_v1beta2_InstanceSpec(in, out, s)
}

func autoConvert_v1beta2_InstanceStatus_To_kudo_InstanceStatus(in *InstanceStatus, out *kudo.InstanceStatus, s conversion.Scope) error {
	out.PlanStatus = *(*map[string]kudo.PlanStatus)(unsafe.Pointer(&in.PlanStatus))
	return nil
}

// Convert_v1beta2_InstanceStatus_To_kudo_InstanceStatus is an autogenerated conversion function.
func Convert_v1beta2_InstanceStatus_To_kudo_InstanceStatus(in *InstanceStatus, out *kudo.InstanceStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_InstanceStatus_To_kudo_InstanceStatus(in, out, s)
}

func autoConvert_kudo_InstanceStatus_To_v1beta2_InstanceStatus(in *kudo.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	out.PlanStatus = *(*map[string]PlanStatus)(unsafe.Pointer(&in.PlanStatus))
	return nil
}

// Convert_kudo_InstanceStatus_To_v1beta2_InstanceStatus is an autogenerated conversion function.
func Convert_kudo_InstanceStatus_To_v1beta2_InstanceStatus(in *kudo.InstanceStatus, out *InstanceStatus, s conversion.Scope) error {
	return autoConvert_kudo_InstanceStatus_To_v1beta2_InstanceStatus(in, out, s)
}

func autoConvert_v1beta2_KudoOperatorTaskSpec_To_kudo_KudoOperatorTaskSpec(in *KudoOperatorTaskSpec, out *kudo.KudoOperatorTaskSpec, s conversion.Scope) error {
	out.Package = in.Package
	out.InstanceName = in.InstanceName
	out.AppVersion = in.AppVersion
	out.OperatorVersion = in.OperatorVersion
	out.ParameterFile = in.ParameterFile
	return nil
}

// Convert_v1beta2_KudoOperatorTaskSpec_To_kudo_KudoOperatorTaskSpec is an autogenerated conversion function.
func Convert_v1beta2_KudoOperatorTaskSpec_To_kudo_KudoOperatorTaskSpec(in *KudoOperatorTaskSpec, out *kudo.KudoOperatorTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_KudoOperatorTaskSpec_To_kudo_KudoOperatorTaskSpec(in, out, s)
}

func autoConvert_kudo_KudoOperatorTaskSpec_To_v1beta2_KudoOperatorTaskSpec(in *kudo.KudoOperatorTaskSpec, out *KudoOperatorTaskSpec, s conversion.Scope) error {
	out.Package = in.Package
	out.InstanceName = in.InstanceName
	out.AppVersion = in.AppVersion
	out.OperatorVersion = in.OperatorVersion
	out.ParameterFile = in.ParameterFile
	return nil
}

// Convert_kudo_KudoOperatorTaskSpec_To_v1beta2_KudoOperatorTaskSpec is an autogenerated conversion function.
func Convert_kudo_KudoOperatorTaskSpec_To_v1beta2_KudoOperatorTaskSpec(in *kudo.KudoOperatorTaskSpec, out *KudoOperatorTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_KudoOperatorTaskSpec_To_v1beta2_KudoOperatorTaskSpec(in, out, s)
}

func autoConvert_v1beta2_Maintainer_To_kudo_Maintainer(in *Maintainer, out *kudo.Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Email = in.Email
	return nil
}

// Convert_v1beta2_Maintainer_To_kudo_Maintainer is an autogenerated conversion function.
func Convert_v1beta2_Maintainer_To_kudo_Maintainer(in *Maintainer, out *kudo.Maintainer, s conversion.Scope) error {
	return autoConvert_v1beta2_Maintainer_To_kudo_Maintainer(in, out, s)
}

func autoConvert_kudo_Maintainer_To_v1beta2_Maintainer(in *kudo.Maintainer, out *Maintainer, s conversion.Scope) error {
	out.Name = in.Name
	out.Email = in.Email
	return nil
}

// Convert_kudo_Maintainer_To_v1beta2_Maintainer is an autogenerated conversion function.
func Convert_kudo_Maintainer_To_v1beta2_Maintainer(in *kudo.Maintainer, out *Maintainer, s conversion.Scope) error {
	return autoConvert_kudo_Maintainer_To_v1beta2_Maintainer(in, out, s)
}

func autoConvert_v1beta2_Operator_To_kudo_Operator(in *Operator, out *kudo.Operator, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OperatorSpec_To_kudo_OperatorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OperatorStatus_To_kudo_OperatorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_Operator_To_kudo_Operator is an autogenerated conversion function.
func Convert_v1beta2_Operator_To_kudo_Operator(in *Operator, out *kudo.Operator, s conversion.Scope) error {
	return autoConvert_v1beta2_Operator_To_kudo_Operator(in, out, s)
}

func autoConvert_kudo_Operator_To_v1beta2_Operator(in *kudo.Operator, out *Operator, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kudo_OperatorSpec_To_v1beta2_OperatorSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kudo_OperatorStatus_To_v1beta2_OperatorStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_Operator_To_v1beta2_Operator is an autogenerated conversion function.
func Convert_kudo_Operator_To_v1beta2_Operator(in *kudo.Operator, out *Operator, s conversion.Scope) error {
	return autoConvert_kudo_Operator_To_v1beta2_Operator(in, out, s)
}

func autoConvert_v1beta2_OperatorList_To_kudo_OperatorList(in *OperatorList, out *kudo.OperatorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kudo.Operator)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_OperatorList_To_kudo_OperatorList is an autogenerated conversion function.
func Convert_v1beta2_OperatorList_To_kudo_OperatorList(in *OperatorList, out *kudo.OperatorList, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorList_To_kudo_OperatorList(in, out, s)
}

func autoConvert_kudo_OperatorList_To_v1beta2_OperatorList(in *kudo.OperatorList, out *OperatorList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Operator)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kudo_OperatorList_To_v1beta2_OperatorList is an autogenerated conversion function.
func Convert_kudo_OperatorList_To_v1beta2_OperatorList(in *kudo.OperatorList, out *OperatorList, s conversion.Scope) error {
	return autoConvert_kudo_OperatorList_To_v1beta2_OperatorList(in, out, s)
}

func autoConvert_v1beta2_OperatorSpec_To_kudo_OperatorSpec(in *OperatorSpec, out *kudo.OperatorSpec, s conversion.Scope) error {
	out.Description = in.Description
	out.KudoVersion = in.KudoVersion
	out.KubernetesVersion = in.KubernetesVersion
	out.Maintainers = *(*[]*kudo.Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.URL = in.URL
	out.NamespaceManifest = in.NamespaceManifest
	return nil
}

// Convert_v1beta2_OperatorSpec_To_kudo_OperatorSpec is an autogenerated conversion function.
func Convert_v1beta2_OperatorSpec_To_kudo_OperatorSpec(in *OperatorSpec, out *kudo.OperatorSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorSpec_To_kudo_OperatorSpec(in, out, s)
}

func autoConvert_kudo_OperatorSpec_To_v1beta2_OperatorSpec(in *kudo.OperatorSpec, out *OperatorSpec, s conversion.Scope) error {
	out.Description = in.Description
	out.KudoVersion = in.KudoVersion
	out.KubernetesVersion = in.KubernetesVersion
	out.Maintainers = *(*[]*Maintainer)(unsafe.Pointer(&in.Maintainers))
	out.URL = in.URL
	out.NamespaceManifest = in.NamespaceManifest
	return nil
}

// Convert_kudo_OperatorSpec_To_v1beta2_OperatorSpec is an autogenerated conversion function.
func Convert_kudo_OperatorSpec_To_v1beta2_OperatorSpec(in *kudo.OperatorSpec, out *OperatorSpec, s conversion.Scope) error {
	return autoConvert_kudo_OperatorSpec_To_v1beta2_OperatorSpec(in, out, s)
}

func autoConvert_v1beta2_OperatorStatus_To_kudo_OperatorStatus(in *OperatorStatus, out *kudo.OperatorStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_OperatorStatus_To_kudo_OperatorStatus is an autogenerated conversion function.
func Convert_v1beta2_OperatorStatus_To_kudo_OperatorStatus(in *OperatorStatus, out *kudo.OperatorStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorStatus_To_kudo_OperatorStatus(in, out, s)
}

func autoConvert_kudo_OperatorStatus_To_v1beta2_OperatorStatus(in *kudo.OperatorStatus, out *OperatorStatus, s conversion.Scope) error {
	return nil
}

// Convert_kudo_OperatorStatus_To_v1beta2_OperatorStatus is an autogenerated conversion function.
func Convert_kudo_OperatorStatus_To_v1beta2_OperatorStatus(in *kudo.OperatorStatus, out *OperatorStatus, s conversion.Scope) error {
	return autoConvert_kudo_OperatorStatus_To_v1beta2_OperatorStatus(in, out, s)
}

func autoConvert_v1beta2_OperatorVersion_To_kudo_OperatorVersion(in *OperatorVersion, out *kudo.OperatorVersion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_OperatorVersionSpec_To_kudo_OperatorVersionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_OperatorVersionStatus_To_kudo_OperatorVersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_OperatorVersion_To_kudo_OperatorVersion is an autogenerated conversion function.
func Convert_v1beta2_OperatorVersion_To_kudo_OperatorVersion(in *OperatorVersion, out *kudo.OperatorVersion, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorVersion_To_kudo_OperatorVersion(in, out, s)
}

func autoConvert_kudo_OperatorVersion_To_v1beta2_OperatorVersion(in *kudo.OperatorVersion, out *OperatorVersion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_kudo_OperatorVersionSpec_To_v1beta2_OperatorVersionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_kudo_OperatorVersionStatus_To_v1beta2_OperatorVersionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_OperatorVersion_To_v1beta2_OperatorVersion is an autogenerated conversion function.
func Convert_kudo_OperatorVersion_To_v1beta2_OperatorVersion(in *kudo.OperatorVersion, out *OperatorVersion, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersion_To_v1beta2_OperatorVersion(in, out, s)
}

func autoConvert_v1beta2_OperatorVersionList_To_kudo_OperatorVersionList(in *OperatorVersionList, out *kudo.OperatorVersionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]kudo.OperatorVersion)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_OperatorVersionList_To_kudo_OperatorVersionList is an autogenerated conversion function.
func Convert_v1beta2_OperatorVersionList_To_kudo_OperatorVersionList(in *OperatorVersionList, out *kudo.OperatorVersionList, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorVersionList_To_kudo_OperatorVersionList(in, out, s)
}

func autoConvert_kudo_OperatorVersionList_To_v1beta2_OperatorVersionList(in *kudo.OperatorVersionList, out *OperatorVersionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OperatorVersion)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_kudo_OperatorVersionList_To_v1beta2_OperatorVersionList is an autogenerated conversion function.
func Convert_kudo_OperatorVersionList_To_v1beta2_OperatorVersionList(in *kudo.OperatorVersionList, out *OperatorVersionList, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersionList_To_v1beta2_OperatorVersionList(in, out, s)
}

func autoConvert_v1beta2_OperatorVersionSpec_To_kudo_OperatorVersionSpec(in *OperatorVersionSpec, out *kudo.OperatorVersionSpec, s conversion.Scope) error {
	out.Operator = in.Operator
	out.Version = in.Version
	out.AppVersion = in.AppVersion
	out.Templates = *(*map[string]string)(unsafe.Pointer(&in.Templates))
	out.Tasks = *(*[]kudo.Task)(unsafe.Pointer(&in.Tasks))
	out.Parameters = in.Parameters
	out.Plans = *(*map[string]kudo.Plan)(unsafe.Pointer(&in.Plans))
	out.ConnectionString = in.ConnectionString
	out.UpgradableFrom = *(*[]v1.ObjectReference)(unsafe.Pointer(&in.UpgradableFrom))
	return nil
}

// Convert_v1beta2_OperatorVersionSpec_To_kudo_OperatorVersionSpec is an autogenerated conversion function.
func Convert_v1beta2_OperatorVersionSpec_To_kudo_OperatorVersionSpec(in *OperatorVersionSpec, out *kudo.OperatorVersionSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorVersionSpec_To_kudo_OperatorVersionSpec(in, out, s)
}

func autoConvert_kudo_OperatorVersionSpec_To_v1beta2_OperatorVersionSpec(in *kudo.OperatorVersionSpec, out *OperatorVersionSpec, s conversion.Scope) error {
	out.Operator = in.Operator
	out.Version = in.Version
	out.AppVersion = in.AppVersion
	out.Templates = *(*map[string]string)(unsafe.Pointer(&in.Templates))
	out.Tasks = *(*[]Task)(unsafe.Pointer(&in.Tasks))
	out.Parameters = in.Parameters
	out.Plans = *(*map[string]Plan)(unsafe.Pointer(&in.Plans))
	out.ConnectionString = in.ConnectionString
	out.UpgradableFrom = *(*[]v1.ObjectReference)(unsafe.Pointer(&in.UpgradableFrom))
	return nil
}

// Convert_kudo_OperatorVersionSpec_To_v1beta2_OperatorVersionSpec is an autogenerated conversion function.
func Convert_kudo_OperatorVersionSpec_To_v1beta2_OperatorVersionSpec(in *kudo.OperatorVersionSpec, out *OperatorVersionSpec, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersionSpec_To_v1beta2_OperatorVersionSpec(in, out, s)
}

func autoConvert_v1beta2_OperatorVersionStatus_To_kudo_OperatorVersionStatus(in *OperatorVersionStatus, out *kudo.OperatorVersionStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1beta2_OperatorVersionStatus_To_kudo_OperatorVersionStatus is an autogenerated conversion function.
func Convert_v1beta2_OperatorVersionStatus_To_kudo_OperatorVersionStatus(in *OperatorVersionStatus, out *kudo.OperatorVersionStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_OperatorVersionStatus_To_kudo_OperatorVersionStatus(in, out, s)
}

func autoConvert_kudo_OperatorVersionStatus_To_v1beta2_OperatorVersionStatus(in *kudo.OperatorVersionStatus, out *OperatorVersionStatus, s conversion.Scope) error {
	return nil
}

// Convert_kudo_OperatorVersionStatus_To_v1beta2_OperatorVersionStatus is an autogenerated conversion function.
func Convert_kudo_OperatorVersionStatus_To_v1beta2_OperatorVersionStatus(in *kudo.OperatorVersionStatus, out *OperatorVersionStatus, s conversion.Scope) error {
	return autoConvert_kudo_OperatorVersionStatus_To_v1beta2_OperatorVersionStatus(in, out, s)
}

func autoConvert_v1beta2_Parameter_To_kudo_Parameter(in *Parameter, out *kudo.Parameter, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Name = in.Name
	out.Description = in.Description
	out.Required = (*bool)(unsafe.Pointer(in.Required))
	out.Default = (*string)(unsafe.Pointer(in.Default))
	out.Trigger = in.Trigger
	out.Type = kudo.ParameterType(in.Type)
	out.Immutable = (*bool)(unsafe.Pointer(in.Immutable))
	return nil
}

// Convert_v1beta2_Parameter_To_kudo_Parameter is an autogenerated conversion function.
func Convert_v1beta2_Parameter_To_kudo_Parameter(in *Parameter, out *kudo.Parameter, s conversion.Scope) error {
	return autoConvert_v1beta2_Parameter_To_kudo_Parameter(in, out, s)
}

func autoConvert_kudo_Parameter_To_v1beta2_Parameter(in *kudo.Parameter, out *Parameter, s conversion.Scope) error {
	out.DisplayName = in.DisplayName
	out.Name = in.Name
	out.Description = in.Description
	out.Required = (*bool)(unsafe.Pointer(in.Required))
	out.Default = (*string)(unsafe.Pointer(in.Default))
	out.Trigger = in.Trigger
	out.Type = ParameterType(in.Type)
	out.Immutable = (*bool)(unsafe.Pointer(in.Immutable))
	return nil
}

// Convert_kudo_Parameter_To_v1beta2_Parameter is an autogenerated conversion function.
func Convert_kudo_Parameter_To_v1beta2_Parameter(in *kudo.Parameter, out *Parameter, s conversion.Scope) error {
	return autoConvert_kudo_Parameter_To_v1beta2_Parameter(in, out, s)
}

func autoConvert_v1beta2_Phase_To_kudo_Phase(in *Phase, out *kudo.Phase, s conversion.Scope) error {
	out.Name = in.Name
	out.Strategy = kudo.Ordering(in.Strategy)
	out.Steps = *(*[]kudo.Step)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_v1beta2_Phase_To_kudo_Phase is an autogenerated conversion function.
func Convert_v1beta2_Phase_To_kudo_Phase(in *Phase, out *kudo.Phase, s conversion.Scope) error {
	return autoConvert_v1beta2_Phase_To_kudo_Phase(in, out, s)
}

func autoConvert_kudo_Phase_To_v1beta2_Phase(in *kudo.Phase, out *Phase, s conversion.Scope) error {
	out.Name = in.Name
	out.Strategy = Ordering(in.Strategy)
	out.Steps = *(*[]Step)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_kudo_Phase_To_v1beta2_Phase is an autogenerated conversion function.
func Convert_kudo_Phase_To_v1beta2_Phase(in *kudo.Phase, out *Phase, s conversion.Scope) error {
	return autoConvert_kudo_Phase_To_v1beta2_Phase(in, out, s)
}

func autoConvert_v1beta2_PhaseStatus_To_kudo_PhaseStatus(in *PhaseStatus, out *kudo.PhaseStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = kudo.ExecutionStatus(in.Status)
	out.Message = in.Message
	out.Steps = *(*[]kudo.StepStatus)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_v1beta2_PhaseStatus_To_kudo_PhaseStatus is an autogenerated conversion function.
func Convert_v1beta2_PhaseStatus_To_kudo_PhaseStatus(in *PhaseStatus, out *kudo.PhaseStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_PhaseStatus_To_kudo_PhaseStatus(in, out, s)
}

func autoConvert_kudo_PhaseStatus_To_v1beta2_PhaseStatus(in *kudo.PhaseStatus, out *PhaseStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = ExecutionStatus(in.Status)
	out.Message = in.Message
	out.Steps = *(*[]StepStatus)(unsafe.Pointer(&in.Steps))
	return nil
}

// Convert_kudo_PhaseStatus_To_v1beta2_PhaseStatus is an autogenerated conversion function.
func Convert_kudo_PhaseStatus_To_v1beta2_PhaseStatus(in *kudo.PhaseStatus, out *PhaseStatus, s conversion.Scope) error {
	return autoConvert_kudo_PhaseStatus_To_v1beta2_PhaseStatus(in, out, s)
}

func autoConvert_v1beta2_PipeSpec_To_kudo_PipeSpec(in *PipeSpec, out *kudo.PipeSpec, s conversion.Scope) error {
	out.File = in.File
	out.EnvFile = in.EnvFile
	out.Kind = in.Kind
	out.Key = in.Key
	return nil
}

// Convert_v1beta2_PipeSpec_To_kudo_PipeSpec is an autogenerated conversion function.
func Convert_v1beta2_PipeSpec_To_kudo_PipeSpec(in *PipeSpec, out *kudo.PipeSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_PipeSpec_To_kudo_PipeSpec(in, out, s)
}

func autoConvert_kudo_PipeSpec_To_v1beta2_PipeSpec(in *kudo.PipeSpec, out *PipeSpec, s conversion.Scope) error {
	out.File = in.File
	out.EnvFile = in.EnvFile
	out.Kind = in.Kind
	out.Key = in.Key
	return nil
}

// Convert_kudo_PipeSpec_To_v1beta2_PipeSpec is an autogenerated conversion function.
func Convert_kudo_PipeSpec_To_v1beta2_PipeSpec(in *kudo.PipeSpec, out *PipeSpec, s conversion.Scope) error {
	return autoConvert_kudo_PipeSpec_To_v1beta2_PipeSpec(in, out, s)
}

func autoConvert_v1beta2_PipeTaskSpec_To_kudo_PipeTaskSpec(in *PipeTaskSpec, out *kudo.PipeTaskSpec, s conversion.Scope) error {
	out.Pod = in.Pod
	out.Pipe = *(*[]kudo.PipeSpec)(unsafe.Pointer(&in.Pipe))
	return nil
}

// Convert_v1beta2_PipeTaskSpec_To_kudo_PipeTaskSpec is an autogenerated conversion function.
func Convert_v1beta2_PipeTaskSpec_To_kudo_PipeTaskSpec(in *PipeTaskSpec, out *kudo.PipeTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_PipeTaskSpec_To_kudo_PipeTaskSpec(in, out, s)
}

func autoConvert_kudo_PipeTaskSpec_To_v1beta2_PipeTaskSpec(in *kudo.PipeTaskSpec, out *PipeTaskSpec, s conversion.Scope) error {
	out.Pod = in.Pod
	out.Pipe = *(*[]PipeSpec)(unsafe.Pointer(&in.Pipe))
	return nil
}

// Convert_kudo_PipeTaskSpec_To_v1beta2_PipeTaskSpec is an autogenerated conversion function.
func Convert_kudo_PipeTaskSpec_To_v1beta2_PipeTaskSpec(in *kudo.PipeTaskSpec, out *PipeTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_PipeTaskSpec_To_v1beta2_PipeTaskSpec(in, out, s)
}

func autoConvert_v1beta2_Plan_To_kudo_Plan(in *Plan, out *kudo.Plan, s conversion.Scope) error {
	out.Strategy = kudo.Ordering(in.Strategy)
	out.Phases = *(*[]kudo.Phase)(unsafe.Pointer(&in.Phases))
	return nil
}

// Convert_v1beta2_Plan_To_kudo_Plan is an autogenerated conversion function.
func Convert_v1beta2_Plan_To_kudo_Plan(in *Plan, out *kudo.Plan, s conversion.Scope) error {
	return autoConvert_v1beta2_Plan_To_kudo_Plan(in, out, s)
}

func autoConvert_kudo_Plan_To_v1beta2_Plan(in *kudo.Plan, out *Plan, s conversion.Scope) error {
	out.Strategy = Ordering(in.Strategy)
	out.Phases = *(*[]Phase)(unsafe.Pointer(&in.Phases))
	return nil
}

// Convert_kudo_Plan_To_v1beta2_Plan is an autogenerated conversion function.
func Convert_kudo_Plan_To_v1beta2_Plan(in *kudo.Plan, out *Plan, s conversion.Scope) error {
	return autoConvert_kudo_Plan_To_v1beta2_Plan(in, out, s)
}

func autoConvert_v1beta2_PlanExecution_To_kudo_PlanExecution(in *PlanExecution, out *kudo.PlanExecution, s conversion.Scope) error {
	out.PlanName = in.PlanName
	out.UID = types.UID(in.UID)
	out.Status = kudo.ExecutionStatus(in.Status)
	return nil
}

// Convert_v1beta2_PlanExecution_To_kudo_PlanExecution is an autogenerated conversion function.
func Convert_v1beta2_PlanExecution_To_kudo_PlanExecution(in *PlanExecution, out *kudo.PlanExecution, s conversion.Scope) error {
	return autoConvert_v1beta2_PlanExecution_To_kudo_PlanExecution(in, out, s)
}

func autoConvert_kudo_PlanExecution_To_v1beta2_PlanExecution(in *kudo.PlanExecution, out *PlanExecution, s conversion.Scope) error {
	out.PlanName = in.PlanName
	out.UID = types.UID(in.UID)
	out.Status = ExecutionStatus(in.Status)
	return nil
}

// Convert_kudo_PlanExecution_To_v1beta2_PlanExecution is an autogenerated conversion function.
func Convert_kudo_PlanExecution_To_v1beta2_PlanExecution(in *kudo.PlanExecution, out *PlanExecution, s conversion.Scope) error {
	return autoConvert_kudo_PlanExecution_To_v1beta2_PlanExecution(in, out, s)
}

func autoConvert_v1beta2_PlanStatus_To_kudo_PlanStatus(in *PlanStatus, out *kudo.PlanStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = kudo.ExecutionStatus(in.Status)
	out.Message = in.Message
	out.LastUpdatedTimestamp = (*metav1.Time)(unsafe.Pointer(in.LastUpdatedTimestamp))
	out.Phases = *(*[]kudo.PhaseStatus)(unsafe.Pointer(&in.Phases))
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_v1beta2_PlanStatus_To_kudo_PlanStatus is an autogenerated conversion function.
func Convert_v1beta2_PlanStatus_To_kudo_PlanStatus(in *PlanStatus, out *kudo.PlanStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_PlanStatus_To_kudo_PlanStatus(in, out, s)
}

func autoConvert_kudo_PlanStatus_To_v1beta2_PlanStatus(in *kudo.PlanStatus, out *PlanStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Status = ExecutionStatus(in.Status)
	out.Message = in.Message
	out.LastUpdatedTimestamp = (*metav1.Time)(unsafe.Pointer(in.LastUpdatedTimestamp))
	out.Phases = *(*[]PhaseStatus)(unsafe.Pointer(&in.Phases))
	out.UID = types.UID(in.UID)
	return nil
}

// Convert_kudo_PlanStatus_To_v1beta2_PlanStatus is an autogenerated conversion function.
func Convert_kudo_PlanStatus_To_v1beta2_PlanStatus(in *kudo.PlanStatus, out *PlanStatus, s conversion.Scope) error {
	return autoConvert_kudo_PlanStatus_To_v1beta2_PlanStatus(in, out, s)
}

func autoConvert_v1beta2_ResourceTaskSpec_To_kudo_ResourceTaskSpec(in *ResourceTaskSpec, out *kudo.ResourceTaskSpec, s conversion.Scope) error {
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1beta2_ResourceTaskSpec_To_kudo_ResourceTaskSpec is an autogenerated conversion function.
func Convert_v1beta2_ResourceTaskSpec_To_kudo_ResourceTaskSpec(in *ResourceTaskSpec, out *kudo.ResourceTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_ResourceTaskSpec_To_kudo_ResourceTaskSpec(in, out, s)
}

func autoConvert_kudo_ResourceTaskSpec_To_v1beta2_ResourceTaskSpec(in *kudo.ResourceTaskSpec, out *ResourceTaskSpec, s conversion.Scope) error {
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_kudo_ResourceTaskSpec_To_v1beta2_ResourceTaskSpec is an autogenerated conversion function.
func Convert_kudo_ResourceTaskSpec_To_v1beta2_ResourceTaskSpec(in *kudo.ResourceTaskSpec, out *ResourceTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_ResourceTaskSpec_To_v1beta2_ResourceTaskSpec(in, out, s)
}

func autoConvert_v1beta2_Step_To_kudo_Step(in *Step, out *kudo.Step, s conversion.Scope) error {
	out.Name = in.Name
	out.Tasks = *(*[]string)(unsafe.Pointer(&in.Tasks))
	return nil
}

// Convert_v1beta2_Step_To_kudo_Step is an autogenerated conversion function.
func Convert_v1beta2_Step_To_kudo_Step(in *Step, out *kudo.Step, s conversion.Scope) error {
	return autoConvert_v1beta2_Step_To_kudo_Step(in, out, s)
}

func autoConvert_kudo_Step_To_v1beta2_Step(in *kudo.Step, out *Step, s conversion.Scope) error {
	out.Name = in.Name
	out.Tasks = *(*[]string)(unsafe.Pointer(&in.Tasks))
	return nil
}

// Convert_kudo_Step_To_v1beta2_Step is an autogenerated conversion function.
func Convert_kudo_Step_To_v1beta2_Step(in *kudo.Step, out *Step, s conversion.Scope) error {
	return autoConvert_kudo_Step_To_v1beta2_Step(in, out, s)
}

func autoConvert_v1beta2_StepStatus_To_kudo_StepStatus(in *StepStatus, out *kudo.StepStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Message = in.Message
	out.Status = kudo.ExecutionStatus(in.Status)
	return nil
}

// Convert_v1beta2_StepStatus_To_kudo_StepStatus is an autogenerated conversion function.
func Convert_v1beta2_StepStatus_To_kudo_StepStatus(in *StepStatus, out *kudo.StepStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_StepStatus_To_kudo_StepStatus(in, out, s)
}

func autoConvert_kudo_StepStatus_To_v1beta2_StepStatus(in *kudo.StepStatus, out *StepStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Message = in.Message
	out.Status = ExecutionStatus(in.Status)
	return nil
}

// Convert_kudo_StepStatus_To_v1beta2_StepStatus is an autogenerated conversion function.
func Convert_kudo_StepStatus_To_v1beta2_StepStatus(in *kudo.StepStatus, out *StepStatus, s conversion.Scope) error {
	return autoConvert_kudo_StepStatus_To_v1beta2_StepStatus(in, out, s)
}

func autoConvert_v1beta2_Task_To_kudo_Task(in *Task, out *kudo.Task, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	if err := Convert_v1beta2_TaskSpec_To_kudo_TaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_Task_To_kudo_Task is an autogenerated conversion function.
func Convert_v1beta2_Task_To_kudo_Task(in *Task, out *kudo.Task, s conversion.Scope) error {
	return autoConvert_v1beta2_Task_To_kudo_Task(in, out, s)
}

func autoConvert_kudo_Task_To_v1beta2_Task(in *kudo.Task, out *Task, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	if err := Convert_kudo_TaskSpec_To_v1beta2_TaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_Task_To_v1beta2_Task is an autogenerated conversion function.
func Convert_kudo_Task_To_v1beta2_Task(in *kudo.Task, out *Task, s conversion.Scope) error {
	return autoConvert_kudo_Task_To_v1beta2_Task(in, out, s)
}

func autoConvert_v1beta2_TaskSpec_To_kudo_TaskSpec(in *TaskSpec, out *kudo.TaskSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_ResourceTaskSpec_To_kudo_ResourceTaskSpec(&in.ResourceTaskSpec, &out.ResourceTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_DummyTaskSpec_To_kudo_DummyTaskSpec(&in.DummyTaskSpec, &out.DummyTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_PipeTaskSpec_To_kudo_PipeTaskSpec(&in.PipeTaskSpec, &out.PipeTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_ToggleTaskSpec_To_kudo_ToggleTaskSpec(&in.ToggleTaskSpec, &out.ToggleTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_KudoOperatorTaskSpec_To_kudo_KudoOperatorTaskSpec(&in.KudoOperatorTaskSpec, &out.KudoOperatorTaskSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_TaskSpec_To_kudo_TaskSpec is an autogenerated conversion function.
func Convert_v1beta2_TaskSpec_To_kudo_TaskSpec(in *TaskSpec, out *kudo.TaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_TaskSpec_To_kudo_TaskSpec(in, out, s)
}

func autoConvert_kudo_TaskSpec_To_v1beta2_TaskSpec(in *kudo.TaskSpec, out *TaskSpec, s conversion.Scope) error {
	if err := Convert_kudo_ResourceTaskSpec_To_v1beta2_ResourceTaskSpec(&in.ResourceTaskSpec, &out.ResourceTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_kudo_DummyTaskSpec_To_v1beta2_DummyTaskSpec(&in.DummyTaskSpec, &out.DummyTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_kudo_PipeTaskSpec_To_v1beta2_PipeTaskSpec(&in.PipeTaskSpec, &out.PipeTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_kudo_ToggleTaskSpec_To_v1beta2_ToggleTaskSpec(&in.ToggleTaskSpec, &out.ToggleTaskSpec, s); err != nil {
		return err
	}
	if err := Convert_kudo_KudoOperatorTaskSpec_To_v1beta2_KudoOperatorTaskSpec(&in.KudoOperatorTaskSpec, &out.KudoOperatorTaskSpec, s); err != nil {
		return err
	}
	return nil
}

// Convert_kudo_TaskSpec_To_v1beta2_TaskSpec is an autogenerated conversion function.
func Convert_kudo_TaskSpec_To_v1beta2_TaskSpec(in *kudo.TaskSpec, out *TaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_TaskSpec_To_v1beta2_TaskSpec(in, out, s)
}

func autoConvert_v1beta2_ToggleTaskSpec_To_kudo_ToggleTaskSpec(in *ToggleTaskSpec, out *kudo.ToggleTaskSpec, s conversion.Scope) error {
	out.Parameter = in.Parameter
	return nil
}

// Convert_v1beta2_ToggleTaskSpec_To_kudo_ToggleTaskSpec is an autogenerated conversion function.
func Convert_v1beta2_ToggleTaskSpec_To_kudo_ToggleTaskSpec(in *ToggleTaskSpec, out *kudo.ToggleTaskSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_ToggleTaskSpec_To_kudo_ToggleTaskSpec(in, out, s)
}

func autoConvert_kudo_ToggleTaskSpec_To_v1beta2_ToggleTaskSpec(in *kudo.ToggleTaskSpec, out *ToggleTaskSpec, s conversion.Scope) error {
	out.Parameter = in.Parameter
	return nil
}

// Convert_kudo_ToggleTaskSpec_To_v1beta2_ToggleTaskSpec is an autogenerated conversion function.
func Convert_kudo_ToggleTaskSpec_To_v1beta2_ToggleTaskSpec(in *kudo.ToggleTaskSpec, out *ToggleTaskSpec, s conversion.Scope) error {
	return autoConvert_kudo_ToggleTaskSpec_To_v1beta2_ToggleTaskSpec(in, out, s)
}
